// Generated by jextract

package tech.kayys.gollek.llama;

import java.lang.invoke.*;
import java.lang.foreign.*;

/**
 * {@snippet lang = c : * typedef bool (*llama_progress_callback)(float, void *)
 * }
 */
public class llama_progress_callback {

    llama_progress_callback() {
        // Should not be called directly
    }

    /**
     * The function pointer signature, expressed as a functional interface
     */
    public interface Function {
        boolean apply(float progress, MemorySegment user_data);
    }

    private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            llama_h.C_BOOL,
            llama_h.C_FLOAT,
            llama_h.C_POINTER);

    /**
     * The descriptor of this function pointer
     */
    public static FunctionDescriptor descriptor() {
        return $DESC;
    }

    private static final MethodHandle UP$MH = llama_h.upcallHandle(llama_progress_callback.Function.class, "apply",
            $DESC);

    /**
     * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
     * The lifetime of the returned segment is managed by {@code arena}
     */
    public static MemorySegment allocate(llama_progress_callback.Function fi, Arena arena) {
        return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
    }

    private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

    /**
     * Invoke the upcall stub {@code funcPtr}, with given parameters
     */
    public static boolean invoke(MemorySegment funcPtr, float progress, MemorySegment user_data) {
        try {
            return (boolean) DOWN$MH.invokeExact(funcPtr, progress, user_data);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
}
