// Generated by jextract

package tech.kayys.gollek.llama;

import java.lang.foreign.*;
import java.util.function.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang = c :
 * struct llama_sampler {
 *     const struct llama_sampler_i *iface;
 *     llama_sampler_context_t ctx;
 * }
 * }
 */
public class llama_sampler {

    llama_sampler() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
            llama_h.C_POINTER.withName("iface"),
            llama_h.C_POINTER.withName("ctx")).withName("llama_sampler");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final AddressLayout iface$LAYOUT = (AddressLayout) $LAYOUT.select(groupElement("iface"));

    /**
     * Layout for field:
     * {@snippet lang = c : * const struct llama_sampler_i *iface
     * }
     */
    public static final AddressLayout iface$layout() {
        return iface$LAYOUT;
    }

    private static final long iface$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang = c : * const struct llama_sampler_i *iface
     * }
     */
    public static final long iface$offset() {
        return iface$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang = c : * const struct llama_sampler_i *iface
     * }
     */
    public static MemorySegment iface(MemorySegment struct) {
        return struct.get(iface$LAYOUT, iface$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang = c : * const struct llama_sampler_i *iface
     * }
     */
    public static void iface(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(iface$LAYOUT, iface$OFFSET, fieldValue);
    }

    private static final AddressLayout ctx$LAYOUT = (AddressLayout) $LAYOUT.select(groupElement("ctx"));

    /**
     * Layout for field:
     * {@snippet lang = c : * llama_sampler_context_t ctx
     * }
     */
    public static final AddressLayout ctx$layout() {
        return ctx$LAYOUT;
    }

    private static final long ctx$OFFSET = 8;

    /**
     * Offset for field:
     * {@snippet lang = c : * llama_sampler_context_t ctx
     * }
     */
    public static final long ctx$offset() {
        return ctx$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang = c : * llama_sampler_context_t ctx
     * }
     */
    public static MemorySegment ctx(MemorySegment struct) {
        return struct.get(ctx$LAYOUT, ctx$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang = c : * llama_sampler_context_t ctx
     * }
     */
    public static void ctx(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(ctx$LAYOUT, ctx$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at
     * {@code index}.
     * The returned segment has address
     * {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() {
        return layout().byteSize();
    }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using
     * {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and
     * {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and
     * {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena,
            Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}
