#!/bin/bash
# Gollek - Local Development Installer
# Builds the CLI from source and installs a local shim for testing.
# Usage: ./install-local.sh

set -e

# --- Configuration ---
PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CLI_MODULE="ui/gollek-cli"
BIN_DIR="${HOME}/.local/bin"
GOLLEK_CLI_BIN="${BIN_DIR}/gollek"

# --- Visuals ---
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo -e "${BLUE}--------------------------------------------------${NC}"
echo -e "${GREEN} Gollek Local Installer (Dev Mode) ${NC}"
echo -e "${BLUE}--------------------------------------------------${NC}"

# 1. Build the project
echo -e "${BLUE}>>> Building Gollek project...${NC}"
if [ -f "./build.sh" ]; then
    ./build.sh -c
else
    echo -e "${YELLOW}build.sh not found, running mvn directly...${NC}"
    mvn clean install -DskipTests
fi

# 2. Locate the JAR
echo -e "${BLUE}>>> Locating CLI artifacts...${NC}"
JAR_PATH="${PROJECT_ROOT}/${CLI_MODULE}/target/gollek-runner.jar"

if [ ! -f "$JAR_PATH" ]; then
    # Try alternate location if finalName was changed
    JAR_PATH=$(find "${PROJECT_ROOT}/${CLI_MODULE}/target" -name "gollek*.jar" | head -n 1)
fi

if [ -z "$JAR_PATH" ] || [ ! -f "$JAR_PATH" ]; then
    echo -e "${RED}❌ Could not find Gollek CLI JAR in ${CLI_MODULE}/target${NC}"
    exit 1
fi

echo -e "${GREEN}✓ Found JAR: $(basename "$JAR_PATH")${NC}"

# 3. Create Local Bin Directory
mkdir -p "$BIN_DIR"

# 4. Create the Shim Script
echo -e "${BLUE}>>> Creating shim at ${GOLLEK_CLI_BIN}...${NC}"

cat <<EOF > "$GOLLEK_CLI_BIN"
#!/bin/bash
# Local Gollek CLI Shim (Generated by install-local.sh)
# Points to: $JAR_PATH

# Ensure Java 25 is used if possible
if [ -s "\$HOME/.sdkman/bin/sdkman-init.sh" ]; then
    source "\$HOME/.sdkman/bin/sdkman-init.sh"
    sdk use java 25-open >/dev/null 2>&1 || true
fi

exec java \
    --add-modules jdk.incubator.vector \
    -Djava.library.path="\$HOME/.gollek/libs/llama:\$HOME/.gollek/libs/onnxruntime:\$HOME/.gollek/libs/libtorch" \
    -jar "$JAR_PATH" "\$@"
EOF

chmod +x "$GOLLEK_CLI_BIN"

# 5. Final Instructions
echo ""
echo -e "${GREEN}✅ Gollek CLI installed locally to ${GOLLEK_CLI_BIN}${NC}"
echo ""

if [[ ":$PATH:" != *":$BIN_DIR:"* ]]; then
    echo -e "${YELLOW}⚠ ${BIN_DIR} is not in your PATH.${NC}"
    echo -e "Add this to your .zshrc or .bashrc:"
    echo -e "  ${BLUE}export PATH=\"\$HOME/.local/bin:\$PATH\"${NC}"
    echo ""
fi

echo -e "Try running: ${YELLOW}gollek --version${NC}"
echo -e "${BLUE}--------------------------------------------------${NC}"
