#!/bin/bash
# Gollek - Local Development Installer
# Builds the CLI from source and installs a local shim for testing.
# Usage: ./install-local.sh [--native]

set -e

# --- Configuration ---
PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CLI_MODULE="ui/gollek-cli"
BIN_DIR="${HOME}/.local/bin"
GOLLEK_CLI_BIN="${BIN_DIR}/gollek"
NATIVE_MODE=false

# --- Visuals ---
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# --- Parse Arguments ---
while [[ "$#" -gt 0 ]]; do
    case $1 in
        -n|--native) NATIVE_MODE=true ;;
        -h|--help) 
            echo "Usage: $0 [options]"
            echo ""
            echo "Options:"
            echo "  -n, --native    Build and install as native executable (requires GraalVM)"
            echo "  -h, --help      Show this help message"
            exit 0 
            ;;
    esac
    shift
done

echo -e "${BLUE}--------------------------------------------------${NC}"
echo -e "${GREEN} Gollek Local Installer (Dev Mode) ${NC}"
if [ "$NATIVE_MODE" = true ]; then
    echo -e "${YELLOW} Mode: Native (GraalVM) ${NC}"
else
    echo -e "${YELLOW} Mode: JVM (Standard JAR) ${NC}"
fi
echo -e "${BLUE}--------------------------------------------------${NC}"

# 1. Build the project
echo -e "${BLUE}>>> Building Gollek project...${NC}"
if [ -f "./build.sh" ]; then
    if [ "$NATIVE_MODE" = true ]; then
        ./build.sh -c -n
    else
        ./build.sh -c
    fi
else
    echo -e "${YELLOW}build.sh not found, running mvn directly...${NC}"
    if [ "$NATIVE_MODE" = true ]; then
        mvn clean install -DskipTests -Pnative
    else
        mvn clean install -DskipTests
    fi
fi

# 2. Locate Artifacts
echo -e "${BLUE}>>> Locating CLI artifacts...${NC}"

if [ "$NATIVE_MODE" = true ]; then
    # Locate Native Executable
    NATIVE_PATH="${PROJECT_ROOT}/${CLI_MODULE}/target/gollek-runner"
    if [ ! -f "$NATIVE_PATH" ]; then
        # Try alternate location
        NATIVE_PATH=$(find "${PROJECT_ROOT}/${CLI_MODULE}/target" -name "gollek" -type f -not -name "*.jar" | head -n 1)
    fi

    if [ -z "$NATIVE_PATH" ] || [ ! -f "$NATIVE_PATH" ]; then
        echo -e "${RED}❌ Could not find native executable in ${CLI_MODULE}/target${NC}"
        exit 1
    fi
    echo -e "${GREEN}✓ Found Native Binary: $(basename "$NATIVE_PATH")${NC}"
else
    # Locate JAR
    JAR_PATH="${PROJECT_ROOT}/${CLI_MODULE}/target/gollek-runner.jar"
    if [ ! -f "$JAR_PATH" ]; then
        JAR_PATH=$(find "${PROJECT_ROOT}/${CLI_MODULE}/target" -name "gollek*.jar" | head -n 1)
    fi

    if [ -z "$JAR_PATH" ] || [ ! -f "$JAR_PATH" ]; then
        echo -e "${RED}❌ Could not find Gollek CLI JAR in ${CLI_MODULE}/target${NC}"
        exit 1
    fi
    echo -e "${GREEN}✓ Found JAR: $(basename "$JAR_PATH")${NC}"
fi

# 3. Create Local Bin Directory
mkdir -p "$BIN_DIR"

# 4. Create the Shim/Binary link
echo -e "${BLUE}>>> Creating executable at ${GOLLEK_CLI_BIN}...${NC}"

if [ "$NATIVE_MODE" = true ]; then
    # For native, we create a shim that sets library paths but calls the binary directly
    cat <<EOF > "$GOLLEK_CLI_BIN"
#!/bin/bash
# Local Gollek CLI Native Shim (Generated by install-local.sh)
# Points to: $NATIVE_PATH

# Ensure log directory exists
mkdir -p "\$HOME/.gollek/logs"

# Set library path for native libs (llama.cpp, ONNX, LibTorch)
export DYLD_LIBRARY_PATH="\$HOME/.gollek/libs/llama:\$HOME/.gollek/libs/onnxruntime:\$HOME/.gollek/libs/libtorch:\$DYLD_LIBRARY_PATH"
export LD_LIBRARY_PATH="\$HOME/.gollek/libs/llama:\$HOME/.gollek/libs/onnxruntime:\$HOME/.gollek/libs/libtorch:\$LD_LIBRARY_PATH"

# Launch native binary
exec "$NATIVE_PATH" "\$@"
EOF
else
    # Standard JAR Shim
    cat <<EOF > "$GOLLEK_CLI_BIN"
#!/bin/bash
# Local Gollek CLI Shim (Generated by install-local.sh)
# Points to: $JAR_PATH

# Ensure Java 25 is used if possible
if [ -s "\$HOME/.sdkman/bin/sdkman-init.sh" ]; then
    source "\$HOME/.sdkman/bin/sdkman-init.sh"
    sdk use java 25-open >/dev/null 2>&1 || true
fi

# Ensure log directory exists
mkdir -p "\$HOME/.gollek/logs"

# Launch — suppress JVM incubator warning from stderr
exec java \\
    --add-modules jdk.incubator.vector \\
    -Djava.library.path="\$HOME/.gollek/libs/llama:\$HOME/.gollek/libs/onnxruntime:\$HOME/.gollek/libs/libtorch" \\
    -jar "$JAR_PATH" "\$@" 2> >(grep -v "WARNING: Using incubator modules" >&2)
EOF
fi

chmod +x "$GOLLEK_CLI_BIN"

# 5. Final Instructions
echo ""
echo -e "${GREEN}✅ Gollek CLI installed locally to ${GOLLEK_CLI_BIN}${NC}"
echo ""

if [[ ":$PATH:" != *":$BIN_DIR:"* ]]; then
    echo -e "${YELLOW}⚠ ${BIN_DIR} is not in your PATH.${NC}"
    echo -e "Add this to your .zshrc or .bashrc:"
    echo -e "  ${BLUE}export PATH=\"\$HOME/.local/bin:\$PATH\"${NC}"
    echo ""
fi

echo -e "Try running: ${YELLOW}gollek --version${NC}"
echo -e "${BLUE}--------------------------------------------------${NC}"
