rootProject.name = "gollek-engine"

fun includeOptionalProject(projectPath: String, vararg candidatePaths: String) {
    val projectDir = candidatePaths
        .map { file(it) }
        .firstOrNull { candidate ->
            candidate.resolve("build.gradle.kts").isFile || candidate.resolve("build.gradle").isFile
        }
        ?: return

    include(projectPath)
    project(":$projectPath").projectDir = projectDir
}

include("gollek-utils")
include("compiler:gollek-compiler")
include("compiler:gollek-neural-compiler")
include("core:gollek-adapter")
include("core:gollek-core")
include("core:gollek-distributed")
include("core:gollek-error-code")
include("core:gollek-ir")
    include("core:gollek-ir-schema")
include("core:gollek-model-database")
include("core:gollek-model-repository")
include("core:gollek-model-repo-hf")
include("core:gollek-model-repo-kaggle")
include("core:gollek-model-repo-local")
include("core:gollek-model-runner")
include("core:gollek-multitenancy")
include("core:gollek-observability")
include("core:gollek-provider-core")
include("core:gollek-provider-routing")
include("core:gollek-runtime-config")
include("core:gollek-tensor")
include("core:gollek-tokenizer-core")
include("core:gollek-tool-core")
include("examples:jupyter-deps")
include("integration:gollek-jupyter-kernel")
project(":integration:gollek-jupyter-kernel").projectDir = file("integration/jupyter/gollek-jupyter-kernel")
include("models:gollek-model-cohere")
include("models:gollek-model-common")
include("models:gollek-model-deepseek")
include("models:gollek-model-gemma")
include("models:gollek-model-kimi")
include("models:gollek-model-llama")
include("models:gollek-model-mistral")
include("models:gollek-model-phi")
include("models:gollek-model-qwen")
include("models:gollek-model-yii")
val staticallyIncludedModelProjects = setOf(
    "gollek-model-cohere",
    "gollek-model-common",
    "gollek-model-deepseek",
    "gollek-model-gemma",
    "gollek-model-kimi",
    "gollek-model-llama",
    "gollek-model-mistral",
    "gollek-model-phi",
    "gollek-model-qwen",
    "gollek-model-yii",
)
file("models")
    .listFiles { candidate ->
        candidate.isDirectory &&
                candidate.name.startsWith("gollek-model-") &&
                candidate.name !in staticallyIncludedModelProjects &&
                (candidate.resolve("build.gradle.kts").isFile || candidate.resolve("build.gradle").isFile)
    }
    ?.sortedBy { it.name }
    ?.forEach { modelProject ->
        includeOptionalProject("models:${modelProject.name}", "models/${modelProject.name}")
    }
includeOptionalProject("suling", "../extensions/audio/suling", "stubs/suling")
include("optimization:gollek-plugin-elastic-ep")
// include("optimization:gollek-plugin-evicpress")
include("optimization:gollek-plugin-fa3")
include("optimization:gollek-plugin-fa4")
// include("optimization:gollek-plugin-hybrid-attn")
include("optimization:gollek-plugin-kv-cache")
include("optimization:gollek-plugin-paged-attention")
// include("optimization:gollek-plugin-perfmode")
// include("optimization:gollek-plugin-prefill-decode")
// include("optimization:gollek-plugin-prompt-cache")
include("optimization:gollek-plugin-qlora")
// include("optimization:gollek-plugin-wait-scheduler")
// include("optimization:gollek-plugin-weight-offload")
include("plugins:gollek-plugin-content-safety")
include("plugins:gollek-plugin-mcp")
include("plugins:gollek-plugin-model-router")
// include("plugins:gollek-plugin-observability")
// include("plugins:gollek-plugin-pii-redaction")
// include("plugins:gollek-plugin-prompt")
// include("plugins:gollek-plugin-quota")
// include("plugins:gollek-plugin-rag")
// include("plugins:gollek-plugin-reasoning")
// include("plugins:gollek-plugin-sampling")
include("plugins:gollek-plugin-semantic-cache")
// include("plugins:gollek-plugin-streaming")
// include("plugins:gollek-safetensor-rag")
include("plugins:log-parser")
include("plugins:gamelan")
// include("provider:gollek-plugin-anthropic")
// include("provider:gollek-plugin-cerebras")
// include("provider:gollek-plugin-gemini")
include("provider:gollek-plugin-mistral")
include("provider:gollek-plugin-openai")
include("quantizer:gollek-quantizer-autoround")
include("quantizer:gollek-quantizer-awq")
include("quantizer:gollek-quantizer-gptq")
include("quantizer:gollek-quantizer-quip")
include("quantizer:gollek-quantizer-turboquant")
include("runner:gollek-diffusion")
include("runtime:gollek-runtime")
include("runtime:gollek-runtime-distributed")
include("sdk:gollek-sdk")
include("sdk:gollek-sdk-agent")
include("sdk:gollek-sdk-api")
include("sdk:gollek-sdk-core")
include("sdk:gollek-sdk-local")
include("sdk:gollek-sdk-remote")
if (file("sdk/gollek-sdk-session").isDirectory) {
    include("sdk:gollek-sdk-session")
}
include("spi:gollek-spi")
include("spi:gollek-spi-inference")
include("spi:gollek-spi-model")
include("spi:gollek-spi-multimodal")
include("spi:gollek-spi-plugin")
include("spi:gollek-spi-provider")
include("spi:gollek-spi-runtime")
include("ml:gollek-ml-nlp")
project(":ml:gollek-ml-nlp").projectDir = file("training/gollek-nlp")
include("ml:gollek-ml-nn")
project(":ml:gollek-ml-nn").projectDir = file("training/gollek-nn")
include("ml:gollek-ml-audio")
project(":ml:gollek-ml-audio").projectDir = file("training/gollek-nn-audio")
include("ml:gollek-ml-cnn")
project(":ml:gollek-ml-cnn").projectDir = file("training/gollek-nn-cnn")
include("ml:gollek-ml-multimodal")
project(":ml:gollek-ml-multimodal").projectDir = file("training/gollek-nn-multimodal")
include("ml:gollek-ml-optimize")
project(":ml:gollek-ml-optimize").projectDir = file("training/gollek-nn-optimize")
include("ml:gollek-ml-rnn")
project(":ml:gollek-ml-rnn").projectDir = file("training/gollek-nn-rnn")
include("ml:gollek-ml-vision")
project(":ml:gollek-ml-vision").projectDir = file("training/gollek-nn-vision")
include("ml:gollek-ml-serialization")
project(":ml:gollek-ml-serialization").projectDir = file("training/gollek-serializer")
include("trainer:gollek-trainer")
project(":trainer:gollek-trainer").projectDir = file("trainer/gollek-trainer")
include("trainer:gollek-trainer-api")
project(":trainer:gollek-trainer-api").projectDir = file("trainer/gollek-trainer-api")
include("ml:gollek-ml-api")
project(":ml:gollek-ml-api").projectDir = file("training/gollek-train-api")
include("ml:gollek-ml-runner-api")
include("ml:gollek-ml-autograd")
include("ml:gollek-ml-core")
include("ml:gollek-ml-byte-latent")
include("ml:gollek-ml-persistence")
include("ml:gollek-ml-selection")
include("ml:gollek-ml-export")
include("ml:gollek-ml-hub")
include("ml:gollek-ml-data")
project(":ml:gollek-ml-data").projectDir = file("training/gollek-train-data")
include("ml:gollek-ml-diffusion-api")
project(":ml:gollek-ml-diffusion-api").projectDir = file("training/gollek-train-diffusion-api")
include("ml:gollek-ml-diffusion-opd")
project(":ml:gollek-ml-diffusion-opd").projectDir = file("training/gollek-train-diffusion-opd")
include("ml:gollek-ml-estimator")
project(":ml:gollek-ml-estimator").projectDir = file("training/gollek-train-estimator")
include("ml:gollek-ml-recursive-reasoning")
project(":ml:gollek-ml-recursive-reasoning").projectDir = file("training/gollek-train-recursive-reasoning")
include("examples:gollek-ml-examples")
project(":examples:gollek-ml-examples").projectDir = file("training/gollek-train-examples")
include("ml:gollek-ml-preprocessing")
project(":ml:gollek-ml-preprocessing").projectDir = file("training/gollek-train-transformer")
include("ui:gollek-api")
include("ui:gollek-cli")
include("backend:blackwell:gollek-kernel-blackwell")
include("backend:blackwell:gollek-plugin-kernel-blackwell")
include("backend:cpu:gollek-backend-cpu")
include("backend:cuda:gollek-backend-cuda")
include("backend:cuda:gollek-kernel-cuda")
include("backend:cuda:gollek-plugin-kernel-cuda")
include("backend:directml:gollek-plugin-kernel-directml")
include("backend:metal:gollek-backend-metal")
include("backend:metal:gollek-mlx-binding")
include("backend:rocm:gollek-kernel-rocm")
include("backend:rocm:gollek-plugin-kernel-rocm")
include("core:plugin:gollek-plugin-core")
include("core:plugin:gollek-plugin-kernel-core")
include("core:plugin:gollek-plugin-optimization-core")
include("core:plugin:gollek-plugin-runner-core")
include("core:plugin:gollek-plugin-runner-gguf")
include("runner:diffuser:gollek-diffuser")
include("runner:gguf:gollek-gguf-converter")
include("runner:gguf:gollek-gguf-converter-java")
include("runner:gguf:gollek-gguf-core")
include("runner:litert:gollek-litert-core")
include("runner:litert:gollek-plugin-runner-litert")
include("runner:litert:gollek-runner-litert")
include("runner:onnx:gollek-ml-export-onnx")
include("runner:onnx:gollek-ml-onnx")
include("runner:onnx:gollek-plugin-runner-onnx")
include("runner:onnx:gollek-runner-onnx")
include("runner:pickle:gollek-ml-pickle")
include("runner:safetensor:gollek-runner-safetensor")
include("runner:safetensor:gollek-runner-stable-diffusion")
include("runner:safetensor:gollek-safetensor-api")
include("runner:safetensor:gollek-safetensor-core")
include("runner:safetensor:gollek-safetensor-engine")
include("runner:safetensor:gollek-safetensor-loader")
include("runner:safetensor:gollek-safetensor-quantization")
include("runner:safetensor:gollek-safetensor-spi")
include("runner:tensorrt:gollek-runner-tensorrt")
include("runner:tensorrt:gollek-plugin-runner-tensorrt")
include("runner:torch:gollek-runner-libtorch")
include("integration:langchain4j:gollek-langchain4j")
include("engine")
