// Generated by jextract

package tech.kayys.gollek.llama;

/**
 * {@snippet lang = c : * typedef __mbstate_t __darwin_mbstate_t
 * }
 */
public class __darwin_mbstate_t extends __mbstate_t {

    __darwin_mbstate_t() {
        // Should not be called directly
    }
}
