// Generated by jextract

package tech.kayys.gollek.llama;

import java.lang.invoke.*;
import java.lang.foreign.*;

/**
 * {@snippet lang = c
 * : * typedef void (*ggml_opt_epoch_callback)(bool, ggml_opt_context_t, ggml_opt_dataset_t, ggml_opt_result_t, int64_t, int64_t, int64_t)
 * }
 */
public class ggml_opt_epoch_callback {

    ggml_opt_epoch_callback() {
        // Should not be called directly
    }

    /**
     * The function pointer signature, expressed as a functional interface
     */
    public interface Function {
        void apply(boolean train, MemorySegment opt_ctx, MemorySegment dataset, MemorySegment result, long ibatch,
                long ibatch_max, long t_start_us);
    }

    private static final FunctionDescriptor $DESC = FunctionDescriptor.ofVoid(
            llama_h.C_BOOL,
            llama_h.C_POINTER,
            llama_h.C_POINTER,
            llama_h.C_POINTER,
            llama_h.C_LONG_LONG,
            llama_h.C_LONG_LONG,
            llama_h.C_LONG_LONG);

    /**
     * The descriptor of this function pointer
     */
    public static FunctionDescriptor descriptor() {
        return $DESC;
    }

    private static final MethodHandle UP$MH = llama_h.upcallHandle(ggml_opt_epoch_callback.Function.class, "apply",
            $DESC);

    /**
     * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
     * The lifetime of the returned segment is managed by {@code arena}
     */
    public static MemorySegment allocate(ggml_opt_epoch_callback.Function fi, Arena arena) {
        return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
    }

    private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

    /**
     * Invoke the upcall stub {@code funcPtr}, with given parameters
     */
    public static void invoke(MemorySegment funcPtr, boolean train, MemorySegment opt_ctx, MemorySegment dataset,
            MemorySegment result, long ibatch, long ibatch_max, long t_start_us) {
        try {
            DOWN$MH.invokeExact(funcPtr, train, opt_ctx, dataset, result, ibatch, ibatch_max, t_start_us);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
}
