// Generated by jextract

package tech.kayys.gollek.llama;

import java.lang.foreign.*;
import java.util.function.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang = c :
 * struct llama_model_tensor_buft_override {
 *     const char *pattern;
 *     ggml_backend_buffer_type_t buft;
 * }
 * }
 */
public class llama_model_tensor_buft_override {

    llama_model_tensor_buft_override() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
            llama_h.C_POINTER.withName("pattern"),
            llama_h.C_POINTER.withName("buft")).withName("llama_model_tensor_buft_override");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final AddressLayout pattern$LAYOUT = (AddressLayout) $LAYOUT.select(groupElement("pattern"));

    /**
     * Layout for field:
     * {@snippet lang = c : * const char *pattern
     * }
     */
    public static final AddressLayout pattern$layout() {
        return pattern$LAYOUT;
    }

    private static final long pattern$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang = c : * const char *pattern
     * }
     */
    public static final long pattern$offset() {
        return pattern$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang = c : * const char *pattern
     * }
     */
    public static MemorySegment pattern(MemorySegment struct) {
        return struct.get(pattern$LAYOUT, pattern$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang = c : * const char *pattern
     * }
     */
    public static void pattern(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(pattern$LAYOUT, pattern$OFFSET, fieldValue);
    }

    private static final AddressLayout buft$LAYOUT = (AddressLayout) $LAYOUT.select(groupElement("buft"));

    /**
     * Layout for field:
     * {@snippet lang = c : * ggml_backend_buffer_type_t buft
     * }
     */
    public static final AddressLayout buft$layout() {
        return buft$LAYOUT;
    }

    private static final long buft$OFFSET = 8;

    /**
     * Offset for field:
     * {@snippet lang = c : * ggml_backend_buffer_type_t buft
     * }
     */
    public static final long buft$offset() {
        return buft$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang = c : * ggml_backend_buffer_type_t buft
     * }
     */
    public static MemorySegment buft(MemorySegment struct) {
        return struct.get(buft$LAYOUT, buft$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang = c : * ggml_backend_buffer_type_t buft
     * }
     */
    public static void buft(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(buft$LAYOUT, buft$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at
     * {@code index}.
     * The returned segment has address
     * {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() {
        return layout().byteSize();
    }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using
     * {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and
     * {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and
     * {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena,
            Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}
