/**
 * gollek_metal_kernel_source.m — runtime Metal shader source builders.
 */

#import "gollek_metal_kernel_source.h"

NSString* gollek_metal_runtime_kernel_source(void) {
    return
        @"#include <metal_stdlib>\n"
        @"using namespace metal;\n"
        @"constant uint GOLLEK_RMS_THREADS = 256;\n"
        @"constant uint GOLLEK_MATVEC_THREADS = 256;\n"
        @"static inline float gollek_silu_gate(float g) {\n"
        @"    if (g <= -20.0f) return 0.0f;\n"
        @"    if (g >= 20.0f) return g;\n"
        @"    return g / (1.0f + exp(-g));\n"
        @"}\n"
        @"static inline float gollek_gelu_gate(float g) {\n"
        @"    if (g <= -10.0f) return 0.0f;\n"
        @"    if (g >= 10.0f) return g;\n"
        @"    float inner = 0.79788456f * (g + 0.044715f * g * g * g);\n"
        @"    return 0.5f * g * (1.0f + tanh(inner));\n"
        @"}\n"
        @"static inline float gollek_gated_activation(float gate, float up, uint activation_kind) {\n"
        @"    float act = activation_kind == 1u ? gollek_silu_gate(gate) : gollek_gelu_gate(gate);\n"
        @"    float y = act * up;\n"
        @"    return isfinite(y) ? y : 0.0f;\n"
        @"}\n"
        @"kernel void gollek_add_kernel(\n"
        @"    device float* C [[buffer(0)]],\n"
        @"    device const float* A [[buffer(1)]],\n"
        @"    device const float* B [[buffer(2)]],\n"
        @"    constant uint& N [[buffer(3)]],\n"
        @"    uint gid [[thread_position_in_grid]]) {\n"
        @"    if (gid < N) C[gid] = A[gid] + B[gid];\n"
        @"}\n"
        @"kernel void gollek_silu_ffn_kernel(\n"
        @"    device float* out [[buffer(0)]],\n"
        @"    device const float* gate [[buffer(1)]],\n"
        @"    device const float* up [[buffer(2)]],\n"
        @"    constant uint& N [[buffer(3)]],\n"
        @"    uint gid [[thread_position_in_grid]]) {\n"
        @"    if (gid >= N) return;\n"
        @"    float g = gate[gid];\n"
        @"    float act;\n"
        @"    if (g <= -20.0f) {\n"
        @"        act = 0.0f;\n"
        @"    } else if (g >= 20.0f) {\n"
        @"        act = g;\n"
        @"    } else {\n"
        @"        act = g / (1.0f + exp(-g));\n"
        @"    }\n"
        @"    float y = act * up[gid];\n"
        @"    out[gid] = isfinite(y) ? y : 0.0f;\n"
        @"}\n"
        @"kernel void gollek_gelu_ffn_kernel(\n"
        @"    device float* out [[buffer(0)]],\n"
        @"    device const float* gate [[buffer(1)]],\n"
        @"    device const float* up [[buffer(2)]],\n"
        @"    constant uint& N [[buffer(3)]],\n"
        @"    uint gid [[thread_position_in_grid]]) {\n"
        @"    if (gid >= N) return;\n"
        @"    float g = gate[gid];\n"
        @"    float gelu;\n"
        @"    if (g <= -10.0f) {\n"
        @"        gelu = 0.0f;\n"
        @"    } else if (g >= 10.0f) {\n"
        @"        gelu = g;\n"
        @"    } else {\n"
        @"        float inner = 0.79788456f * (g + 0.044715f * g * g * g);\n"
        @"        gelu = 0.5f * g * (1.0f + tanh(inner));\n"
        @"    }\n"
        @"    float y = gelu * up[gid];\n"
        @"    out[gid] = isfinite(y) ? y : 0.0f;\n"
        @"}\n"
        @"kernel void gollek_rmsnorm_kernel(\n"
        @"    device float* out [[buffer(0)]],\n"
        @"    device const float* x [[buffer(1)]],\n"
        @"    device const float* weight [[buffer(2)]],\n"
        @"    constant uint& N [[buffer(3)]],\n"
        @"    constant float& eps [[buffer(4)]],\n"
        @"    constant uint& addOne [[buffer(5)]],\n"
        @"    uint tid [[thread_position_in_threadgroup]]) {\n"
        @"    threadgroup float partial[GOLLEK_RMS_THREADS];\n"
        @"    float ss = 0.0f;\n"
        @"    for (uint i = tid; i < N; i += GOLLEK_RMS_THREADS) {\n"
        @"        float v = x[i];\n"
        @"        ss += v * v;\n"
        @"    }\n"
        @"    partial[tid] = ss;\n"
        @"    threadgroup_barrier(mem_flags::mem_threadgroup);\n"
        @"    for (uint stride = GOLLEK_RMS_THREADS >> 1; stride > 0; stride >>= 1) {\n"
        @"        if (tid < stride) partial[tid] += partial[tid + stride];\n"
        @"        threadgroup_barrier(mem_flags::mem_threadgroup);\n"
        @"    }\n"
        @"    float inv = rsqrt((partial[0] / float(N)) + eps);\n"
        @"    for (uint i = tid; i < N; i += GOLLEK_RMS_THREADS) {\n"
        @"        float w = weight[i] + (addOne != 0 ? 1.0f : 0.0f);\n"
        @"        out[i] = x[i] * inv * w;\n"
        @"    }\n"
        @"}\n"
        @"kernel void gollek_rmsnorm_rows_kernel(\n"
        @"    device float* out [[buffer(0)]],\n"
        @"    device const float* x [[buffer(1)]],\n"
        @"    device const float* weight [[buffer(2)]],\n"
        @"    constant uint& N [[buffer(3)]],\n"
        @"    constant float& eps [[buffer(4)]],\n"
        @"    constant uint& addOne [[buffer(5)]],\n"
        @"    uint row [[threadgroup_position_in_grid]],\n"
        @"    uint tid [[thread_position_in_threadgroup]]) {\n"
        @"    device const float* rowX = x + (row * N);\n"
        @"    device float* rowOut = out + (row * N);\n"
        @"    threadgroup float partial[GOLLEK_RMS_THREADS];\n"
        @"    float ss = 0.0f;\n"
        @"    for (uint i = tid; i < N; i += GOLLEK_RMS_THREADS) {\n"
        @"        float v = rowX[i];\n"
        @"        ss += v * v;\n"
        @"    }\n"
        @"    partial[tid] = ss;\n"
        @"    threadgroup_barrier(mem_flags::mem_threadgroup);\n"
        @"    for (uint stride = GOLLEK_RMS_THREADS >> 1; stride > 0; stride >>= 1) {\n"
        @"        if (tid < stride) partial[tid] += partial[tid + stride];\n"
        @"        threadgroup_barrier(mem_flags::mem_threadgroup);\n"
        @"    }\n"
        @"    float inv = rsqrt((partial[0] / float(N)) + eps);\n"
        @"    for (uint i = tid; i < N; i += GOLLEK_RMS_THREADS) {\n"
        @"        float w = weight[i] + (addOne != 0 ? 1.0f : 0.0f);\n"
        @"        rowOut[i] = rowX[i] * inv * w;\n"
        @"    }\n"
        @"}\n"
        @"kernel void gollek_matvec_tb_half_kernel(\n"
        @"    device float* C [[buffer(0)]],\n"
        @"    device const float* A [[buffer(1)]],\n"
        @"    device const half* B [[buffer(2)]],\n"
        @"    constant uint& K [[buffer(3)]],\n"
        @"    constant uint& N [[buffer(4)]],\n"
        @"    uint gid [[threadgroup_position_in_grid]],\n"
        @"    uint tid [[thread_position_in_threadgroup]]) {\n"
        @"    if (gid >= N) return;\n"
        @"    uint base = gid * K;\n"
        @"    float sum = 0.0f;\n"
        @"    for (uint k = tid; k < K; k += GOLLEK_MATVEC_THREADS) {\n"
        @"        sum += A[k] * float(B[base + k]);\n"
        @"    }\n"
        @"    threadgroup float partial[GOLLEK_MATVEC_THREADS];\n"
        @"    partial[tid] = sum;\n"
        @"    threadgroup_barrier(mem_flags::mem_threadgroup);\n"
        @"    for (uint stride = GOLLEK_MATVEC_THREADS >> 1; stride > 0; stride >>= 1) {\n"
        @"        if (tid < stride) partial[tid] += partial[tid + stride];\n"
        @"        threadgroup_barrier(mem_flags::mem_threadgroup);\n"
        @"    }\n"
        @"    if (tid == 0) C[gid] = partial[0];\n"
        @"}\n"
        @"kernel void gollek_matvec_tb_half_pair_kernel(\n"
        @"    device float* C0 [[buffer(0)]],\n"
        @"    device float* C1 [[buffer(1)]],\n"
        @"    device const float* A [[buffer(2)]],\n"
        @"    device const half* B0 [[buffer(3)]],\n"
        @"    device const half* B1 [[buffer(4)]],\n"
        @"    constant uint& K [[buffer(5)]],\n"
        @"    constant uint& N [[buffer(6)]],\n"
        @"    uint gid [[threadgroup_position_in_grid]],\n"
        @"    uint tid [[thread_position_in_threadgroup]]) {\n"
        @"    if (gid >= N) return;\n"
        @"    uint base = gid * K;\n"
        @"    float sum0 = 0.0f;\n"
        @"    float sum1 = 0.0f;\n"
        @"    for (uint k = tid; k < K; k += GOLLEK_MATVEC_THREADS) {\n"
        @"        float av = A[k];\n"
        @"        sum0 += av * float(B0[base + k]);\n"
        @"        sum1 += av * float(B1[base + k]);\n"
        @"    }\n"
        @"    threadgroup float partial0[GOLLEK_MATVEC_THREADS];\n"
        @"    threadgroup float partial1[GOLLEK_MATVEC_THREADS];\n"
        @"    partial0[tid] = sum0;\n"
        @"    partial1[tid] = sum1;\n"
        @"    threadgroup_barrier(mem_flags::mem_threadgroup);\n"
        @"    for (uint stride = GOLLEK_MATVEC_THREADS >> 1; stride > 0; stride >>= 1) {\n"
        @"        if (tid < stride) {\n"
        @"            partial0[tid] += partial0[tid + stride];\n"
        @"            partial1[tid] += partial1[tid + stride];\n"
        @"        }\n"
        @"        threadgroup_barrier(mem_flags::mem_threadgroup);\n"
        @"    }\n"
        @"    if (tid == 0) {\n"
        @"        C0[gid] = partial0[0];\n"
        @"        C1[gid] = partial1[0];\n"
        @"    }\n"
        @"}\n"
        @"kernel void gollek_matvec_tb_half_gated_pair_kernel(\n"
        @"    device float* C [[buffer(0)]],\n"
        @"    device const float* A [[buffer(1)]],\n"
        @"    device const half* gateW [[buffer(2)]],\n"
        @"    device const half* upW [[buffer(3)]],\n"
        @"    constant uint& K [[buffer(4)]],\n"
        @"    constant uint& N [[buffer(5)]],\n"
        @"    constant uint& activationKind [[buffer(6)]],\n"
        @"    uint gid [[threadgroup_position_in_grid]],\n"
        @"    uint tid [[thread_position_in_threadgroup]]) {\n"
        @"    if (gid >= N) return;\n"
        @"    uint base = gid * K;\n"
        @"    float gate = 0.0f;\n"
        @"    float up = 0.0f;\n"
        @"    for (uint k = tid; k < K; k += GOLLEK_MATVEC_THREADS) {\n"
        @"        float av = A[k];\n"
        @"        gate += av * float(gateW[base + k]);\n"
        @"        up += av * float(upW[base + k]);\n"
        @"    }\n"
        @"    threadgroup float partialGate[GOLLEK_MATVEC_THREADS];\n"
        @"    threadgroup float partialUp[GOLLEK_MATVEC_THREADS];\n"
        @"    partialGate[tid] = gate;\n"
        @"    partialUp[tid] = up;\n"
        @"    threadgroup_barrier(mem_flags::mem_threadgroup);\n"
        @"    for (uint stride = GOLLEK_MATVEC_THREADS >> 1; stride > 0; stride >>= 1) {\n"
        @"        if (tid < stride) {\n"
        @"            partialGate[tid] += partialGate[tid + stride];\n"
        @"            partialUp[tid] += partialUp[tid + stride];\n"
        @"        }\n"
        @"        threadgroup_barrier(mem_flags::mem_threadgroup);\n"
        @"    }\n"
        @"    if (tid == 0) C[gid] = gollek_gated_activation(partialGate[0], partialUp[0], activationKind);\n"
        @"}\n"
        @"kernel void gollek_matvec_tb_half_triple_mixed_kernel(\n"
        @"    device float* C0 [[buffer(0)]],\n"
        @"    device float* C1 [[buffer(1)]],\n"
        @"    device float* C2 [[buffer(2)]],\n"
        @"    device const float* A [[buffer(3)]],\n"
        @"    device const half* B0 [[buffer(4)]],\n"
        @"    device const half* B1 [[buffer(5)]],\n"
        @"    device const half* B2 [[buffer(6)]],\n"
        @"    constant uint& K [[buffer(7)]],\n"
        @"    constant uint& N0 [[buffer(8)]],\n"
        @"    constant uint& N1 [[buffer(9)]],\n"
        @"    constant uint& N2 [[buffer(10)]],\n"
        @"    uint gid [[threadgroup_position_in_grid]],\n"
        @"    uint tid [[thread_position_in_threadgroup]]) {\n"
        @"    uint total = N0 + N1 + N2;\n"
        @"    if (gid >= total) return;\n"
        @"    device const half* B = B0;\n"
        @"    device float* C = C0;\n"
        @"    uint local = gid;\n"
        @"    if (gid >= N0 + N1) {\n"
        @"        B = B2;\n"
        @"        C = C2;\n"
        @"        local = gid - N0 - N1;\n"
        @"    } else if (gid >= N0) {\n"
        @"        B = B1;\n"
        @"        C = C1;\n"
        @"        local = gid - N0;\n"
        @"    }\n"
        @"    uint base = local * K;\n"
        @"    float sum = 0.0f;\n"
        @"    for (uint k = tid; k < K; k += GOLLEK_MATVEC_THREADS) {\n"
        @"        sum += A[k] * float(B[base + k]);\n"
        @"    }\n"
        @"    threadgroup float partial[GOLLEK_MATVEC_THREADS];\n"
        @"    partial[tid] = sum;\n"
        @"    threadgroup_barrier(mem_flags::mem_threadgroup);\n"
        @"    for (uint stride = GOLLEK_MATVEC_THREADS >> 1; stride > 0; stride >>= 1) {\n"
        @"        if (tid < stride) partial[tid] += partial[tid + stride];\n"
        @"        threadgroup_barrier(mem_flags::mem_threadgroup);\n"
        @"    }\n"
        @"    if (tid == 0) C[local] = partial[0];\n"
        @"}\n"
        @"kernel void gollek_decode_attention_kernel(\n"
        @"    device float* out [[buffer(0)]],\n"
        @"    device const float* Q [[buffer(1)]],\n"
        @"    device const float* K_cache [[buffer(2)]],\n"
        @"    device const float* V_cache [[buffer(3)]],\n"
        @"    device const int* block_table [[buffer(4)]],\n"
        @"    device const int* context_lens [[buffer(5)]],\n"
        @"    constant uint& H [[buffer(6)]],\n"
        @"    constant uint& H_kv [[buffer(7)]],\n"
        @"    constant uint& D [[buffer(8)]],\n"
        @"    constant uint& block_size [[buffer(9)]],\n"
        @"    constant uint& max_blocks [[buffer(10)]],\n"
        @"    constant float& scale [[buffer(11)]],\n"
        @"    constant uint& is_causal [[buffer(12)]],\n"
        @"    constant int& query_start_pos [[buffer(13)]],\n"
        @"    constant int& sliding_window [[buffer(14)]],\n"
        @"    constant float& soft_cap [[buffer(15)]],\n"
        @"    uint group [[threadgroup_position_in_grid]],\n"
        @"    uint tid [[thread_position_in_threadgroup]]) {\n"
        @"    threadgroup float scores[4096];\n"
        @"    threadgroup float partial[256];\n"
        @"    uint b = group / H;\n"
        @"    uint h = group - b * H;\n"
        @"    int ctx_len = context_lens[b];\n"
        @"    if (ctx_len <= 0 || H_kv == 0 || D == 0) return;\n"
        @"    uint gqa_group = max(1u, H / H_kv);\n"
        @"    uint kv_h = min(H_kv - 1u, h / gqa_group);\n"
        @"    int abs_query_pos = query_start_pos;\n"
        @"    if (is_causal != 0 && sliding_window <= 0 && query_start_pos == 0) abs_query_pos = ctx_len - 1;\n"
        @"    int max_pos = (is_causal != 0) ? abs_query_pos : (ctx_len - 1);\n"
        @"    if (max_pos >= ctx_len) max_pos = ctx_len - 1;\n"
        @"    int min_pos = sliding_window > 0 ? (abs_query_pos - sliding_window + 1) : 0;\n"
        @"    if (min_pos < 0) min_pos = 0;\n"
        @"    uint valid = max_pos >= min_pos ? uint(max_pos - min_pos + 1) : 0u;\n"
        @"    if (valid == 0u || valid > 4096u) {\n"
        @"        for (uint d = tid; d < D; d += 256u) out[(b * H + h) * D + d] = 0.0f;\n"
        @"        return;\n"
        @"    }\n"
        @"    device const float* qh = Q + (b * H + h) * D;\n"
        @"    float local_max = -3.402823466e+38F;\n"
        @"    for (uint idx = tid; idx < valid; idx += 256u) {\n"
        @"        uint pos = uint(min_pos) + idx;\n"
        @"        uint logical_block = pos / block_size;\n"
        @"        uint block_offset = pos - logical_block * block_size;\n"
        @"        int phys_i = block_table[b * max_blocks + logical_block];\n"
        @"        uint phys = uint(max(phys_i, 0));\n"
        @"        device const float* kh = K_cache + (((phys * H_kv + kv_h) * block_size + block_offset) * D);\n"
        @"        float dot = 0.0f;\n"
        @"        for (uint d = 0u; d < D; d++) dot += qh[d] * kh[d];\n"
        @"        float score = dot * scale;\n"
        @"        if (soft_cap > 0.0f) score = soft_cap * tanh(score / soft_cap);\n"
        @"        scores[idx] = score;\n"
        @"        local_max = max(local_max, score);\n"
        @"    }\n"
        @"    partial[tid] = local_max;\n"
        @"    threadgroup_barrier(mem_flags::mem_threadgroup);\n"
        @"    for (uint stride = 128u; stride > 0u; stride >>= 1u) {\n"
        @"        if (tid < stride) partial[tid] = max(partial[tid], partial[tid + stride]);\n"
        @"        threadgroup_barrier(mem_flags::mem_threadgroup);\n"
        @"    }\n"
        @"    float mx = partial[0];\n"
        @"    float local_sum = 0.0f;\n"
        @"    for (uint idx = tid; idx < valid; idx += 256u) {\n"
        @"        float w = exp(scores[idx] - mx);\n"
        @"        scores[idx] = w;\n"
        @"        local_sum += w;\n"
        @"    }\n"
        @"    partial[tid] = local_sum;\n"
        @"    threadgroup_barrier(mem_flags::mem_threadgroup);\n"
        @"    for (uint stride = 128u; stride > 0u; stride >>= 1u) {\n"
        @"        if (tid < stride) partial[tid] += partial[tid + stride];\n"
        @"        threadgroup_barrier(mem_flags::mem_threadgroup);\n"
        @"    }\n"
        @"    float inv_sum = 1.0f / (partial[0] + 1.0e-9f);\n"
        @"    threadgroup_barrier(mem_flags::mem_threadgroup);\n"
        @"    for (uint d = tid; d < D; d += 256u) {\n"
        @"        float acc = 0.0f;\n"
        @"        for (uint idx = 0u; idx < valid; idx++) {\n"
        @"            uint pos = uint(min_pos) + idx;\n"
        @"            uint logical_block = pos / block_size;\n"
        @"            uint block_offset = pos - logical_block * block_size;\n"
        @"            int phys_i = block_table[b * max_blocks + logical_block];\n"
        @"            uint phys = uint(max(phys_i, 0));\n"
        @"            device const float* vh = V_cache + (((phys * H_kv + kv_h) * block_size + block_offset) * D);\n"
        @"            acc += (scores[idx] * inv_sum) * vh[d];\n"
        @"        }\n"
        @"        out[(b * H + h) * D + d] = acc;\n"
        @"    }\n"
        @"}\n"
        @"kernel void gollek_matvec_t_half_kernel(\n"
        @"    device float* C [[buffer(0)]],\n"
        @"    device const float* A [[buffer(1)]],\n"
        @"    device const half* B [[buffer(2)]],\n"
        @"    constant uint& K [[buffer(3)]],\n"
        @"    constant uint& N [[buffer(4)]],\n"
        @"    uint gid [[threadgroup_position_in_grid]],\n"
        @"    uint tid [[thread_position_in_threadgroup]]) {\n"
        @"    if (gid >= N) return;\n"
        @"    float sum = 0.0f;\n"
        @"    for (uint k = tid; k < K; k += GOLLEK_MATVEC_THREADS) {\n"
        @"        sum += A[k] * float(B[k * N + gid]);\n"
        @"    }\n"
        @"    threadgroup float partial[GOLLEK_MATVEC_THREADS];\n"
        @"    partial[tid] = sum;\n"
        @"    threadgroup_barrier(mem_flags::mem_threadgroup);\n"
        @"    for (uint stride = GOLLEK_MATVEC_THREADS >> 1; stride > 0; stride >>= 1) {\n"
        @"        if (tid < stride) partial[tid] += partial[tid + stride];\n"
        @"        threadgroup_barrier(mem_flags::mem_threadgroup);\n"
        @"    }\n"
        @"    if (tid == 0) C[gid] = partial[0];\n"
        @"}\n";
}

NSString* gollek_metal_matvec_kernel_source(NSUInteger threads) {
    return [NSString stringWithFormat:
        @"#include <metal_stdlib>\n"
        @"using namespace metal;\n"
        @"constant uint GOLLEK_MATVEC_THREADS = %lu;\n"
        @"static inline float gollek_bf16_to_float(ushort v) {\n"
        @"    return as_type<float>(uint(v) << 16);\n"
        @"}\n"
        @"static inline float gollek_silu_gate(float g) {\n"
        @"    if (g <= -20.0f) return 0.0f;\n"
        @"    if (g >= 20.0f) return g;\n"
        @"    return g / (1.0f + exp(-g));\n"
        @"}\n"
        @"static inline float gollek_gelu_gate(float g) {\n"
        @"    if (g <= -10.0f) return 0.0f;\n"
        @"    if (g >= 10.0f) return g;\n"
        @"    float inner = 0.79788456f * (g + 0.044715f * g * g * g);\n"
        @"    return 0.5f * g * (1.0f + tanh(inner));\n"
        @"}\n"
        @"static inline float gollek_gated_activation(float gate, float up, uint activation_kind) {\n"
        @"    float act = activation_kind == 1u ? gollek_silu_gate(gate) : gollek_gelu_gate(gate);\n"
        @"    float y = act * up;\n"
        @"    return isfinite(y) ? y : 0.0f;\n"
        @"}\n"
        @"kernel void gollek_matvec_tb_half_kernel(\n"
        @"    device float* C [[buffer(0)]],\n"
        @"    device const float* A [[buffer(1)]],\n"
        @"    device const half* B [[buffer(2)]],\n"
        @"    constant uint& K [[buffer(3)]],\n"
        @"    constant uint& N [[buffer(4)]],\n"
        @"    uint gid [[threadgroup_position_in_grid]],\n"
        @"    uint tid [[thread_position_in_threadgroup]]) {\n"
        @"    if (gid >= N) return;\n"
        @"    uint base = gid * K;\n"
        @"    float sum = 0.0f;\n"
        @"    for (uint k = tid; k < K; k += GOLLEK_MATVEC_THREADS) {\n"
        @"        sum += A[k] * float(B[base + k]);\n"
        @"    }\n"
        @"    threadgroup float partial[GOLLEK_MATVEC_THREADS];\n"
        @"    partial[tid] = sum;\n"
        @"    threadgroup_barrier(mem_flags::mem_threadgroup);\n"
        @"    for (uint stride = GOLLEK_MATVEC_THREADS >> 1; stride > 0; stride >>= 1) {\n"
        @"        if (tid < stride) partial[tid] += partial[tid + stride];\n"
        @"        threadgroup_barrier(mem_flags::mem_threadgroup);\n"
        @"    }\n"
        @"    if (tid == 0) C[gid] = partial[0];\n"
        @"}\n"
        @"kernel void gollek_matvec_tb_half_pair_kernel(\n"
        @"    device float* C0 [[buffer(0)]],\n"
        @"    device float* C1 [[buffer(1)]],\n"
        @"    device const float* A [[buffer(2)]],\n"
        @"    device const half* B0 [[buffer(3)]],\n"
        @"    device const half* B1 [[buffer(4)]],\n"
        @"    constant uint& K [[buffer(5)]],\n"
        @"    constant uint& N [[buffer(6)]],\n"
        @"    uint gid [[threadgroup_position_in_grid]],\n"
        @"    uint tid [[thread_position_in_threadgroup]]) {\n"
        @"    if (gid >= N) return;\n"
        @"    uint base = gid * K;\n"
        @"    float sum0 = 0.0f;\n"
        @"    float sum1 = 0.0f;\n"
        @"    for (uint k = tid; k < K; k += GOLLEK_MATVEC_THREADS) {\n"
        @"        float av = A[k];\n"
        @"        sum0 += av * float(B0[base + k]);\n"
        @"        sum1 += av * float(B1[base + k]);\n"
        @"    }\n"
        @"    threadgroup float partial0[GOLLEK_MATVEC_THREADS];\n"
        @"    threadgroup float partial1[GOLLEK_MATVEC_THREADS];\n"
        @"    partial0[tid] = sum0;\n"
        @"    partial1[tid] = sum1;\n"
        @"    threadgroup_barrier(mem_flags::mem_threadgroup);\n"
        @"    for (uint stride = GOLLEK_MATVEC_THREADS >> 1; stride > 0; stride >>= 1) {\n"
        @"        if (tid < stride) {\n"
        @"            partial0[tid] += partial0[tid + stride];\n"
        @"            partial1[tid] += partial1[tid + stride];\n"
        @"        }\n"
        @"        threadgroup_barrier(mem_flags::mem_threadgroup);\n"
        @"    }\n"
        @"    if (tid == 0) {\n"
        @"        C0[gid] = partial0[0];\n"
        @"        C1[gid] = partial1[0];\n"
        @"    }\n"
        @"}\n"
        @"kernel void gollek_matvec_tb_half_gated_pair_kernel(\n"
        @"    device float* C [[buffer(0)]],\n"
        @"    device const float* A [[buffer(1)]],\n"
        @"    device const half* gateW [[buffer(2)]],\n"
        @"    device const half* upW [[buffer(3)]],\n"
        @"    constant uint& K [[buffer(4)]],\n"
        @"    constant uint& N [[buffer(5)]],\n"
        @"    constant uint& activationKind [[buffer(6)]],\n"
        @"    uint gid [[threadgroup_position_in_grid]],\n"
        @"    uint tid [[thread_position_in_threadgroup]]) {\n"
        @"    if (gid >= N) return;\n"
        @"    uint base = gid * K;\n"
        @"    float gate = 0.0f;\n"
        @"    float up = 0.0f;\n"
        @"    for (uint k = tid; k < K; k += GOLLEK_MATVEC_THREADS) {\n"
        @"        float av = A[k];\n"
        @"        gate += av * float(gateW[base + k]);\n"
        @"        up += av * float(upW[base + k]);\n"
        @"    }\n"
        @"    threadgroup float partialGate[GOLLEK_MATVEC_THREADS];\n"
        @"    threadgroup float partialUp[GOLLEK_MATVEC_THREADS];\n"
        @"    partialGate[tid] = gate;\n"
        @"    partialUp[tid] = up;\n"
        @"    threadgroup_barrier(mem_flags::mem_threadgroup);\n"
        @"    for (uint stride = GOLLEK_MATVEC_THREADS >> 1; stride > 0; stride >>= 1) {\n"
        @"        if (tid < stride) {\n"
        @"            partialGate[tid] += partialGate[tid + stride];\n"
        @"            partialUp[tid] += partialUp[tid + stride];\n"
        @"        }\n"
        @"        threadgroup_barrier(mem_flags::mem_threadgroup);\n"
        @"    }\n"
        @"    if (tid == 0) C[gid] = gollek_gated_activation(partialGate[0], partialUp[0], activationKind);\n"
        @"}\n"
        @"kernel void gollek_matvec_tb_half_triple_mixed_kernel(\n"
        @"    device float* C0 [[buffer(0)]],\n"
        @"    device float* C1 [[buffer(1)]],\n"
        @"    device float* C2 [[buffer(2)]],\n"
        @"    device const float* A [[buffer(3)]],\n"
        @"    device const half* B0 [[buffer(4)]],\n"
        @"    device const half* B1 [[buffer(5)]],\n"
        @"    device const half* B2 [[buffer(6)]],\n"
        @"    constant uint& K [[buffer(7)]],\n"
        @"    constant uint& N0 [[buffer(8)]],\n"
        @"    constant uint& N1 [[buffer(9)]],\n"
        @"    constant uint& N2 [[buffer(10)]],\n"
        @"    uint gid [[threadgroup_position_in_grid]],\n"
        @"    uint tid [[thread_position_in_threadgroup]]) {\n"
        @"    uint total = N0 + N1 + N2;\n"
        @"    if (gid >= total) return;\n"
        @"    device const half* B = B0;\n"
        @"    device float* C = C0;\n"
        @"    uint local = gid;\n"
        @"    if (gid >= N0 + N1) {\n"
        @"        B = B2;\n"
        @"        C = C2;\n"
        @"        local = gid - N0 - N1;\n"
        @"    } else if (gid >= N0) {\n"
        @"        B = B1;\n"
        @"        C = C1;\n"
        @"        local = gid - N0;\n"
        @"    }\n"
        @"    uint base = local * K;\n"
        @"    float sum = 0.0f;\n"
        @"    for (uint k = tid; k < K; k += GOLLEK_MATVEC_THREADS) {\n"
        @"        sum += A[k] * float(B[base + k]);\n"
        @"    }\n"
        @"    threadgroup float partial[GOLLEK_MATVEC_THREADS];\n"
        @"    partial[tid] = sum;\n"
        @"    threadgroup_barrier(mem_flags::mem_threadgroup);\n"
        @"    for (uint stride = GOLLEK_MATVEC_THREADS >> 1; stride > 0; stride >>= 1) {\n"
        @"        if (tid < stride) partial[tid] += partial[tid + stride];\n"
        @"        threadgroup_barrier(mem_flags::mem_threadgroup);\n"
        @"    }\n"
        @"    if (tid == 0) C[local] = partial[0];\n"
        @"}\n"
        @"kernel void gollek_matvec_tb_bf16_kernel(\n"
        @"    device float* C [[buffer(0)]],\n"
        @"    device const float* A [[buffer(1)]],\n"
        @"    device const ushort* B [[buffer(2)]],\n"
        @"    constant uint& K [[buffer(3)]],\n"
        @"    constant uint& N [[buffer(4)]],\n"
        @"    uint gid [[threadgroup_position_in_grid]],\n"
        @"    uint tid [[thread_position_in_threadgroup]]) {\n"
        @"    if (gid >= N) return;\n"
        @"    uint base = gid * K;\n"
        @"    float sum = 0.0f;\n"
        @"    for (uint k = tid; k < K; k += GOLLEK_MATVEC_THREADS) {\n"
        @"        sum += A[k] * gollek_bf16_to_float(B[base + k]);\n"
        @"    }\n"
        @"    threadgroup float partial[GOLLEK_MATVEC_THREADS];\n"
        @"    partial[tid] = sum;\n"
        @"    threadgroup_barrier(mem_flags::mem_threadgroup);\n"
        @"    for (uint stride = GOLLEK_MATVEC_THREADS >> 1; stride > 0; stride >>= 1) {\n"
        @"        if (tid < stride) partial[tid] += partial[tid + stride];\n"
        @"        threadgroup_barrier(mem_flags::mem_threadgroup);\n"
        @"    }\n"
        @"    if (tid == 0) C[gid] = partial[0];\n"
        @"}\n"
        @"kernel void gollek_matvec_tb_bf16_x4_kernel(\n"
        @"    device float* C [[buffer(0)]],\n"
        @"    device const float* A [[buffer(1)]],\n"
        @"    device const ushort* B [[buffer(2)]],\n"
        @"    constant uint& K [[buffer(3)]],\n"
        @"    constant uint& N [[buffer(4)]],\n"
        @"    uint group [[threadgroup_position_in_grid]],\n"
        @"    uint tid [[thread_position_in_threadgroup]]) {\n"
        @"    uint row0 = group * 4u;\n"
        @"    uint row1 = row0 + 1u;\n"
        @"    uint row2 = row0 + 2u;\n"
        @"    uint row3 = row0 + 3u;\n"
        @"    if (row0 >= N) return;\n"
        @"    uint base0 = row0 * K;\n"
        @"    uint base1 = row1 * K;\n"
        @"    uint base2 = row2 * K;\n"
        @"    uint base3 = row3 * K;\n"
        @"    bool has1 = row1 < N;\n"
        @"    bool has2 = row2 < N;\n"
        @"    bool has3 = row3 < N;\n"
        @"    float sum0 = 0.0f;\n"
        @"    float sum1 = 0.0f;\n"
        @"    float sum2 = 0.0f;\n"
        @"    float sum3 = 0.0f;\n"
        @"    for (uint k = tid; k < K; k += GOLLEK_MATVEC_THREADS) {\n"
        @"        float av = A[k];\n"
        @"        sum0 += av * gollek_bf16_to_float(B[base0 + k]);\n"
        @"        if (has1) sum1 += av * gollek_bf16_to_float(B[base1 + k]);\n"
        @"        if (has2) sum2 += av * gollek_bf16_to_float(B[base2 + k]);\n"
        @"        if (has3) sum3 += av * gollek_bf16_to_float(B[base3 + k]);\n"
        @"    }\n"
        @"    threadgroup float p0[GOLLEK_MATVEC_THREADS];\n"
        @"    threadgroup float p1[GOLLEK_MATVEC_THREADS];\n"
        @"    threadgroup float p2[GOLLEK_MATVEC_THREADS];\n"
        @"    threadgroup float p3[GOLLEK_MATVEC_THREADS];\n"
        @"    p0[tid] = sum0;\n"
        @"    p1[tid] = sum1;\n"
        @"    p2[tid] = sum2;\n"
        @"    p3[tid] = sum3;\n"
        @"    threadgroup_barrier(mem_flags::mem_threadgroup);\n"
        @"    for (uint stride = GOLLEK_MATVEC_THREADS >> 1; stride > 0; stride >>= 1) {\n"
        @"        if (tid < stride) {\n"
        @"            p0[tid] += p0[tid + stride];\n"
        @"            p1[tid] += p1[tid + stride];\n"
        @"            p2[tid] += p2[tid + stride];\n"
        @"            p3[tid] += p3[tid + stride];\n"
        @"        }\n"
        @"        threadgroup_barrier(mem_flags::mem_threadgroup);\n"
        @"    }\n"
        @"    if (tid == 0) {\n"
        @"        C[row0] = p0[0];\n"
        @"        if (has1) C[row1] = p1[0];\n"
        @"        if (has2) C[row2] = p2[0];\n"
        @"        if (has3) C[row3] = p3[0];\n"
        @"    }\n"
        @"}\n"
        @"kernel void gollek_matvec_tb_bf16_x4_simd_kernel(\n"
        @"    device float* C [[buffer(0)]],\n"
        @"    device const float* A [[buffer(1)]],\n"
        @"    device const ushort* B [[buffer(2)]],\n"
        @"    constant uint& K [[buffer(3)]],\n"
        @"    constant uint& N [[buffer(4)]],\n"
        @"    uint group [[threadgroup_position_in_grid]],\n"
        @"    uint tid [[thread_position_in_threadgroup]],\n"
        @"    uint lane [[thread_index_in_simdgroup]],\n"
        @"    uint sg [[simdgroup_index_in_threadgroup]]) {\n"
        @"    uint row0 = group * 4u;\n"
        @"    uint row1 = row0 + 1u;\n"
        @"    uint row2 = row0 + 2u;\n"
        @"    uint row3 = row0 + 3u;\n"
        @"    if (row0 >= N) return;\n"
        @"    uint base0 = row0 * K;\n"
        @"    uint base1 = row1 * K;\n"
        @"    uint base2 = row2 * K;\n"
        @"    uint base3 = row3 * K;\n"
        @"    bool has1 = row1 < N;\n"
        @"    bool has2 = row2 < N;\n"
        @"    bool has3 = row3 < N;\n"
        @"    float sum0 = 0.0f;\n"
        @"    float sum1 = 0.0f;\n"
        @"    float sum2 = 0.0f;\n"
        @"    float sum3 = 0.0f;\n"
        @"    for (uint k = tid; k < K; k += GOLLEK_MATVEC_THREADS) {\n"
        @"        float av = A[k];\n"
        @"        sum0 += av * gollek_bf16_to_float(B[base0 + k]);\n"
        @"        if (has1) sum1 += av * gollek_bf16_to_float(B[base1 + k]);\n"
        @"        if (has2) sum2 += av * gollek_bf16_to_float(B[base2 + k]);\n"
        @"        if (has3) sum3 += av * gollek_bf16_to_float(B[base3 + k]);\n"
        @"    }\n"
        @"    threadgroup float p0[8];\n"
        @"    threadgroup float p1[8];\n"
        @"    threadgroup float p2[8];\n"
        @"    threadgroup float p3[8];\n"
        @"    float r0 = simd_sum(sum0);\n"
        @"    float r1 = simd_sum(sum1);\n"
        @"    float r2 = simd_sum(sum2);\n"
        @"    float r3 = simd_sum(sum3);\n"
        @"    if (lane == 0u) {\n"
        @"        p0[sg] = r0;\n"
        @"        p1[sg] = r1;\n"
        @"        p2[sg] = r2;\n"
        @"        p3[sg] = r3;\n"
        @"    }\n"
        @"    threadgroup_barrier(mem_flags::mem_threadgroup);\n"
        @"    if (sg == 0u) {\n"
        @"        uint groups = GOLLEK_MATVEC_THREADS / 32u;\n"
        @"        float v0 = lane < groups ? p0[lane] : 0.0f;\n"
        @"        float v1 = lane < groups ? p1[lane] : 0.0f;\n"
        @"        float v2 = lane < groups ? p2[lane] : 0.0f;\n"
        @"        float v3 = lane < groups ? p3[lane] : 0.0f;\n"
        @"        v0 = simd_sum(v0);\n"
        @"        v1 = simd_sum(v1);\n"
        @"        v2 = simd_sum(v2);\n"
        @"        v3 = simd_sum(v3);\n"
        @"        if (lane == 0u) {\n"
        @"            C[row0] = v0;\n"
        @"            if (has1) C[row1] = v1;\n"
        @"            if (has2) C[row2] = v2;\n"
        @"            if (has3) C[row3] = v3;\n"
        @"        }\n"
        @"    }\n"
        @"}\n"
        @"kernel void gollek_matvec_tb_bf16_x8_kernel(\n"
        @"    device float* C [[buffer(0)]],\n"
        @"    device const float* A [[buffer(1)]],\n"
        @"    device const ushort* B [[buffer(2)]],\n"
        @"    constant uint& K [[buffer(3)]],\n"
        @"    constant uint& N [[buffer(4)]],\n"
        @"    uint group [[threadgroup_position_in_grid]],\n"
        @"    uint tid [[thread_position_in_threadgroup]]) {\n"
        @"    uint row0 = group * 8u;\n"
        @"    uint row1 = row0 + 1u;\n"
        @"    uint row2 = row0 + 2u;\n"
        @"    uint row3 = row0 + 3u;\n"
        @"    uint row4 = row0 + 4u;\n"
        @"    uint row5 = row0 + 5u;\n"
        @"    uint row6 = row0 + 6u;\n"
        @"    uint row7 = row0 + 7u;\n"
        @"    if (row0 >= N) return;\n"
        @"    bool has1 = row1 < N;\n"
        @"    bool has2 = row2 < N;\n"
        @"    bool has3 = row3 < N;\n"
        @"    bool has4 = row4 < N;\n"
        @"    bool has5 = row5 < N;\n"
        @"    bool has6 = row6 < N;\n"
        @"    bool has7 = row7 < N;\n"
        @"    uint base0 = row0 * K;\n"
        @"    uint base1 = row1 * K;\n"
        @"    uint base2 = row2 * K;\n"
        @"    uint base3 = row3 * K;\n"
        @"    uint base4 = row4 * K;\n"
        @"    uint base5 = row5 * K;\n"
        @"    uint base6 = row6 * K;\n"
        @"    uint base7 = row7 * K;\n"
        @"    float sum0 = 0.0f;\n"
        @"    float sum1 = 0.0f;\n"
        @"    float sum2 = 0.0f;\n"
        @"    float sum3 = 0.0f;\n"
        @"    float sum4 = 0.0f;\n"
        @"    float sum5 = 0.0f;\n"
        @"    float sum6 = 0.0f;\n"
        @"    float sum7 = 0.0f;\n"
        @"    for (uint k = tid; k < K; k += GOLLEK_MATVEC_THREADS) {\n"
        @"        float av = A[k];\n"
        @"        sum0 += av * gollek_bf16_to_float(B[base0 + k]);\n"
        @"        if (has1) sum1 += av * gollek_bf16_to_float(B[base1 + k]);\n"
        @"        if (has2) sum2 += av * gollek_bf16_to_float(B[base2 + k]);\n"
        @"        if (has3) sum3 += av * gollek_bf16_to_float(B[base3 + k]);\n"
        @"        if (has4) sum4 += av * gollek_bf16_to_float(B[base4 + k]);\n"
        @"        if (has5) sum5 += av * gollek_bf16_to_float(B[base5 + k]);\n"
        @"        if (has6) sum6 += av * gollek_bf16_to_float(B[base6 + k]);\n"
        @"        if (has7) sum7 += av * gollek_bf16_to_float(B[base7 + k]);\n"
        @"    }\n"
        @"    threadgroup float p0[GOLLEK_MATVEC_THREADS];\n"
        @"    threadgroup float p1[GOLLEK_MATVEC_THREADS];\n"
        @"    threadgroup float p2[GOLLEK_MATVEC_THREADS];\n"
        @"    threadgroup float p3[GOLLEK_MATVEC_THREADS];\n"
        @"    threadgroup float p4[GOLLEK_MATVEC_THREADS];\n"
        @"    threadgroup float p5[GOLLEK_MATVEC_THREADS];\n"
        @"    threadgroup float p6[GOLLEK_MATVEC_THREADS];\n"
        @"    threadgroup float p7[GOLLEK_MATVEC_THREADS];\n"
        @"    p0[tid] = sum0;\n"
        @"    p1[tid] = sum1;\n"
        @"    p2[tid] = sum2;\n"
        @"    p3[tid] = sum3;\n"
        @"    p4[tid] = sum4;\n"
        @"    p5[tid] = sum5;\n"
        @"    p6[tid] = sum6;\n"
        @"    p7[tid] = sum7;\n"
        @"    threadgroup_barrier(mem_flags::mem_threadgroup);\n"
        @"    for (uint stride = GOLLEK_MATVEC_THREADS >> 1; stride > 0; stride >>= 1) {\n"
        @"        if (tid < stride) {\n"
        @"            p0[tid] += p0[tid + stride];\n"
        @"            p1[tid] += p1[tid + stride];\n"
        @"            p2[tid] += p2[tid + stride];\n"
        @"            p3[tid] += p3[tid + stride];\n"
        @"            p4[tid] += p4[tid + stride];\n"
        @"            p5[tid] += p5[tid + stride];\n"
        @"            p6[tid] += p6[tid + stride];\n"
        @"            p7[tid] += p7[tid + stride];\n"
        @"        }\n"
        @"        threadgroup_barrier(mem_flags::mem_threadgroup);\n"
        @"    }\n"
        @"    if (tid == 0) {\n"
        @"        C[row0] = p0[0];\n"
        @"        if (has1) C[row1] = p1[0];\n"
        @"        if (has2) C[row2] = p2[0];\n"
        @"        if (has3) C[row3] = p3[0];\n"
        @"        if (has4) C[row4] = p4[0];\n"
        @"        if (has5) C[row5] = p5[0];\n"
        @"        if (has6) C[row6] = p6[0];\n"
        @"        if (has7) C[row7] = p7[0];\n"
        @"    }\n"
        @"}\n"
        @"kernel void gollek_matvec_tb_bf16_pair_kernel(\n"
        @"    device float* C0 [[buffer(0)]],\n"
        @"    device float* C1 [[buffer(1)]],\n"
        @"    device const float* A [[buffer(2)]],\n"
        @"    device const ushort* B0 [[buffer(3)]],\n"
        @"    device const ushort* B1 [[buffer(4)]],\n"
        @"    constant uint& K [[buffer(5)]],\n"
        @"    constant uint& N [[buffer(6)]],\n"
        @"    uint gid [[threadgroup_position_in_grid]],\n"
        @"    uint tid [[thread_position_in_threadgroup]]) {\n"
        @"    if (gid >= N) return;\n"
        @"    uint base = gid * K;\n"
        @"    float sum0 = 0.0f;\n"
        @"    float sum1 = 0.0f;\n"
        @"    for (uint k = tid; k < K; k += GOLLEK_MATVEC_THREADS) {\n"
        @"        float av = A[k];\n"
        @"        sum0 += av * gollek_bf16_to_float(B0[base + k]);\n"
        @"        sum1 += av * gollek_bf16_to_float(B1[base + k]);\n"
        @"    }\n"
        @"    threadgroup float partial0[GOLLEK_MATVEC_THREADS];\n"
        @"    threadgroup float partial1[GOLLEK_MATVEC_THREADS];\n"
        @"    partial0[tid] = sum0;\n"
        @"    partial1[tid] = sum1;\n"
        @"    threadgroup_barrier(mem_flags::mem_threadgroup);\n"
        @"    for (uint stride = GOLLEK_MATVEC_THREADS >> 1; stride > 0; stride >>= 1) {\n"
        @"        if (tid < stride) {\n"
        @"            partial0[tid] += partial0[tid + stride];\n"
        @"            partial1[tid] += partial1[tid + stride];\n"
        @"        }\n"
        @"        threadgroup_barrier(mem_flags::mem_threadgroup);\n"
        @"    }\n"
        @"    if (tid == 0) {\n"
        @"        C0[gid] = partial0[0];\n"
        @"        C1[gid] = partial1[0];\n"
        @"    }\n"
        @"}\n"
        @"kernel void gollek_matvec_tb_bf16_pair_simd_kernel(\n"
        @"    device float* C0 [[buffer(0)]],\n"
        @"    device float* C1 [[buffer(1)]],\n"
        @"    device const float* A [[buffer(2)]],\n"
        @"    device const ushort* B0 [[buffer(3)]],\n"
        @"    device const ushort* B1 [[buffer(4)]],\n"
        @"    constant uint& K [[buffer(5)]],\n"
        @"    constant uint& N [[buffer(6)]],\n"
        @"    uint gid [[threadgroup_position_in_grid]],\n"
        @"    uint tid [[thread_position_in_threadgroup]],\n"
        @"    uint lane [[thread_index_in_simdgroup]],\n"
        @"    uint sg [[simdgroup_index_in_threadgroup]]) {\n"
        @"    if (gid >= N) return;\n"
        @"    uint base = gid * K;\n"
        @"    float sum0 = 0.0f;\n"
        @"    float sum1 = 0.0f;\n"
        @"    for (uint k = tid; k < K; k += GOLLEK_MATVEC_THREADS) {\n"
        @"        float av = A[k];\n"
        @"        sum0 += av * gollek_bf16_to_float(B0[base + k]);\n"
        @"        sum1 += av * gollek_bf16_to_float(B1[base + k]);\n"
        @"    }\n"
        @"    threadgroup float partial0[8];\n"
        @"    threadgroup float partial1[8];\n"
        @"    float row0 = simd_sum(sum0);\n"
        @"    float row1 = simd_sum(sum1);\n"
        @"    if (lane == 0u) {\n"
        @"        partial0[sg] = row0;\n"
        @"        partial1[sg] = row1;\n"
        @"    }\n"
        @"    threadgroup_barrier(mem_flags::mem_threadgroup);\n"
        @"    if (sg == 0u) {\n"
        @"        uint groups = GOLLEK_MATVEC_THREADS / 32u;\n"
        @"        float v0 = lane < groups ? partial0[lane] : 0.0f;\n"
        @"        float v1 = lane < groups ? partial1[lane] : 0.0f;\n"
        @"        v0 = simd_sum(v0);\n"
        @"        v1 = simd_sum(v1);\n"
        @"        if (lane == 0u) {\n"
        @"            C0[gid] = v0;\n"
        @"            C1[gid] = v1;\n"
        @"        }\n"
        @"    }\n"
        @"}\n"
        @"kernel void gollek_matvec_tb_bf16_pair_x4_kernel(\n"
        @"    device float* C0 [[buffer(0)]],\n"
        @"    device float* C1 [[buffer(1)]],\n"
        @"    device const float* A [[buffer(2)]],\n"
        @"    device const ushort* B0 [[buffer(3)]],\n"
        @"    device const ushort* B1 [[buffer(4)]],\n"
        @"    constant uint& K [[buffer(5)]],\n"
        @"    constant uint& N [[buffer(6)]],\n"
        @"    uint group [[threadgroup_position_in_grid]],\n"
        @"    uint tid [[thread_position_in_threadgroup]]) {\n"
        @"    uint row0 = group * 4u;\n"
        @"    uint row1 = row0 + 1u;\n"
        @"    uint row2 = row0 + 2u;\n"
        @"    uint row3 = row0 + 3u;\n"
        @"    if (row0 >= N) return;\n"
        @"    bool has1 = row1 < N;\n"
        @"    bool has2 = row2 < N;\n"
        @"    bool has3 = row3 < N;\n"
        @"    uint base0 = row0 * K;\n"
        @"    uint base1 = row1 * K;\n"
        @"    uint base2 = row2 * K;\n"
        @"    uint base3 = row3 * K;\n"
        @"    float g0 = 0.0f, g1 = 0.0f, g2 = 0.0f, g3 = 0.0f;\n"
        @"    float u0 = 0.0f, u1 = 0.0f, u2 = 0.0f, u3 = 0.0f;\n"
        @"    for (uint k = tid; k < K; k += GOLLEK_MATVEC_THREADS) {\n"
        @"        float av = A[k];\n"
        @"        g0 += av * gollek_bf16_to_float(B0[base0 + k]);\n"
        @"        u0 += av * gollek_bf16_to_float(B1[base0 + k]);\n"
        @"        if (has1) {\n"
        @"            g1 += av * gollek_bf16_to_float(B0[base1 + k]);\n"
        @"            u1 += av * gollek_bf16_to_float(B1[base1 + k]);\n"
        @"        }\n"
        @"        if (has2) {\n"
        @"            g2 += av * gollek_bf16_to_float(B0[base2 + k]);\n"
        @"            u2 += av * gollek_bf16_to_float(B1[base2 + k]);\n"
        @"        }\n"
        @"        if (has3) {\n"
        @"            g3 += av * gollek_bf16_to_float(B0[base3 + k]);\n"
        @"            u3 += av * gollek_bf16_to_float(B1[base3 + k]);\n"
        @"        }\n"
        @"    }\n"
        @"    threadgroup float pg0[GOLLEK_MATVEC_THREADS];\n"
        @"    threadgroup float pg1[GOLLEK_MATVEC_THREADS];\n"
        @"    threadgroup float pg2[GOLLEK_MATVEC_THREADS];\n"
        @"    threadgroup float pg3[GOLLEK_MATVEC_THREADS];\n"
        @"    threadgroup float pu0[GOLLEK_MATVEC_THREADS];\n"
        @"    threadgroup float pu1[GOLLEK_MATVEC_THREADS];\n"
        @"    threadgroup float pu2[GOLLEK_MATVEC_THREADS];\n"
        @"    threadgroup float pu3[GOLLEK_MATVEC_THREADS];\n"
        @"    pg0[tid] = g0; pg1[tid] = g1; pg2[tid] = g2; pg3[tid] = g3;\n"
        @"    pu0[tid] = u0; pu1[tid] = u1; pu2[tid] = u2; pu3[tid] = u3;\n"
        @"    threadgroup_barrier(mem_flags::mem_threadgroup);\n"
        @"    for (uint stride = GOLLEK_MATVEC_THREADS >> 1; stride > 0; stride >>= 1) {\n"
        @"        if (tid < stride) {\n"
        @"            pg0[tid] += pg0[tid + stride]; pg1[tid] += pg1[tid + stride];\n"
        @"            pg2[tid] += pg2[tid + stride]; pg3[tid] += pg3[tid + stride];\n"
        @"            pu0[tid] += pu0[tid + stride]; pu1[tid] += pu1[tid + stride];\n"
        @"            pu2[tid] += pu2[tid + stride]; pu3[tid] += pu3[tid + stride];\n"
        @"        }\n"
        @"        threadgroup_barrier(mem_flags::mem_threadgroup);\n"
        @"    }\n"
        @"    if (tid == 0) {\n"
        @"        C0[row0] = pg0[0]; C1[row0] = pu0[0];\n"
        @"        if (has1) { C0[row1] = pg1[0]; C1[row1] = pu1[0]; }\n"
        @"        if (has2) { C0[row2] = pg2[0]; C1[row2] = pu2[0]; }\n"
        @"        if (has3) { C0[row3] = pg3[0]; C1[row3] = pu3[0]; }\n"
        @"    }\n"
        @"}\n"
        @"kernel void gollek_matvec_tb_bf16_pair_x4_simd_kernel(\n"
        @"    device float* C0 [[buffer(0)]],\n"
        @"    device float* C1 [[buffer(1)]],\n"
        @"    device const float* A [[buffer(2)]],\n"
        @"    device const ushort* B0 [[buffer(3)]],\n"
        @"    device const ushort* B1 [[buffer(4)]],\n"
        @"    constant uint& K [[buffer(5)]],\n"
        @"    constant uint& N [[buffer(6)]],\n"
        @"    uint group [[threadgroup_position_in_grid]],\n"
        @"    uint tid [[thread_position_in_threadgroup]],\n"
        @"    uint lane [[thread_index_in_simdgroup]],\n"
        @"    uint sg [[simdgroup_index_in_threadgroup]]) {\n"
        @"    uint row0 = group * 4u;\n"
        @"    uint row1 = row0 + 1u;\n"
        @"    uint row2 = row0 + 2u;\n"
        @"    uint row3 = row0 + 3u;\n"
        @"    if (row0 >= N) return;\n"
        @"    bool has1 = row1 < N;\n"
        @"    bool has2 = row2 < N;\n"
        @"    bool has3 = row3 < N;\n"
        @"    uint base0 = row0 * K;\n"
        @"    uint base1 = row1 * K;\n"
        @"    uint base2 = row2 * K;\n"
        @"    uint base3 = row3 * K;\n"
        @"    float g0 = 0.0f, g1 = 0.0f, g2 = 0.0f, g3 = 0.0f;\n"
        @"    float u0 = 0.0f, u1 = 0.0f, u2 = 0.0f, u3 = 0.0f;\n"
        @"    for (uint k = tid; k < K; k += GOLLEK_MATVEC_THREADS) {\n"
        @"        float av = A[k];\n"
        @"        g0 += av * gollek_bf16_to_float(B0[base0 + k]);\n"
        @"        u0 += av * gollek_bf16_to_float(B1[base0 + k]);\n"
        @"        if (has1) {\n"
        @"            g1 += av * gollek_bf16_to_float(B0[base1 + k]);\n"
        @"            u1 += av * gollek_bf16_to_float(B1[base1 + k]);\n"
        @"        }\n"
        @"        if (has2) {\n"
        @"            g2 += av * gollek_bf16_to_float(B0[base2 + k]);\n"
        @"            u2 += av * gollek_bf16_to_float(B1[base2 + k]);\n"
        @"        }\n"
        @"        if (has3) {\n"
        @"            g3 += av * gollek_bf16_to_float(B0[base3 + k]);\n"
        @"            u3 += av * gollek_bf16_to_float(B1[base3 + k]);\n"
        @"        }\n"
        @"    }\n"
        @"    threadgroup float pg0[8], pg1[8], pg2[8], pg3[8];\n"
        @"    threadgroup float pu0[8], pu1[8], pu2[8], pu3[8];\n"
        @"    float rg0 = simd_sum(g0), rg1 = simd_sum(g1), rg2 = simd_sum(g2), rg3 = simd_sum(g3);\n"
        @"    float ru0 = simd_sum(u0), ru1 = simd_sum(u1), ru2 = simd_sum(u2), ru3 = simd_sum(u3);\n"
        @"    if (lane == 0u) {\n"
        @"        pg0[sg] = rg0; pg1[sg] = rg1; pg2[sg] = rg2; pg3[sg] = rg3;\n"
        @"        pu0[sg] = ru0; pu1[sg] = ru1; pu2[sg] = ru2; pu3[sg] = ru3;\n"
        @"    }\n"
        @"    threadgroup_barrier(mem_flags::mem_threadgroup);\n"
        @"    if (sg == 0u) {\n"
        @"        uint groups = GOLLEK_MATVEC_THREADS / 32u;\n"
        @"        float vg0 = lane < groups ? pg0[lane] : 0.0f;\n"
        @"        float vg1 = lane < groups ? pg1[lane] : 0.0f;\n"
        @"        float vg2 = lane < groups ? pg2[lane] : 0.0f;\n"
        @"        float vg3 = lane < groups ? pg3[lane] : 0.0f;\n"
        @"        float vu0 = lane < groups ? pu0[lane] : 0.0f;\n"
        @"        float vu1 = lane < groups ? pu1[lane] : 0.0f;\n"
        @"        float vu2 = lane < groups ? pu2[lane] : 0.0f;\n"
        @"        float vu3 = lane < groups ? pu3[lane] : 0.0f;\n"
        @"        vg0 = simd_sum(vg0); vg1 = simd_sum(vg1); vg2 = simd_sum(vg2); vg3 = simd_sum(vg3);\n"
        @"        vu0 = simd_sum(vu0); vu1 = simd_sum(vu1); vu2 = simd_sum(vu2); vu3 = simd_sum(vu3);\n"
        @"        if (lane == 0u) {\n"
        @"            C0[row0] = vg0; C1[row0] = vu0;\n"
        @"            if (has1) { C0[row1] = vg1; C1[row1] = vu1; }\n"
        @"            if (has2) { C0[row2] = vg2; C1[row2] = vu2; }\n"
        @"            if (has3) { C0[row3] = vg3; C1[row3] = vu3; }\n"
        @"        }\n"
        @"    }\n"
        @"}\n"
        @"kernel void gollek_matvec_tb_bf16_gated_pair_kernel(\n"
        @"    device float* C [[buffer(0)]],\n"
        @"    device const float* A [[buffer(1)]],\n"
        @"    device const ushort* gateW [[buffer(2)]],\n"
        @"    device const ushort* upW [[buffer(3)]],\n"
        @"    constant uint& K [[buffer(4)]],\n"
        @"    constant uint& N [[buffer(5)]],\n"
        @"    constant uint& activationKind [[buffer(6)]],\n"
        @"    uint gid [[threadgroup_position_in_grid]],\n"
        @"    uint tid [[thread_position_in_threadgroup]]) {\n"
        @"    if (gid >= N) return;\n"
        @"    uint base = gid * K;\n"
        @"    float gate = 0.0f;\n"
        @"    float up = 0.0f;\n"
        @"    for (uint k = tid; k < K; k += GOLLEK_MATVEC_THREADS) {\n"
        @"        float av = A[k];\n"
        @"        gate += av * gollek_bf16_to_float(gateW[base + k]);\n"
        @"        up += av * gollek_bf16_to_float(upW[base + k]);\n"
        @"    }\n"
        @"    threadgroup float partialGate[GOLLEK_MATVEC_THREADS];\n"
        @"    threadgroup float partialUp[GOLLEK_MATVEC_THREADS];\n"
        @"    partialGate[tid] = gate;\n"
        @"    partialUp[tid] = up;\n"
        @"    threadgroup_barrier(mem_flags::mem_threadgroup);\n"
        @"    for (uint stride = GOLLEK_MATVEC_THREADS >> 1; stride > 0; stride >>= 1) {\n"
        @"        if (tid < stride) {\n"
        @"            partialGate[tid] += partialGate[tid + stride];\n"
        @"            partialUp[tid] += partialUp[tid + stride];\n"
        @"        }\n"
        @"        threadgroup_barrier(mem_flags::mem_threadgroup);\n"
        @"    }\n"
        @"    if (tid == 0) C[gid] = gollek_gated_activation(partialGate[0], partialUp[0], activationKind);\n"
        @"}\n"
        @"kernel void gollek_matvec_tb_bf16_gated_pair_x4_kernel(\n"
        @"    device float* C [[buffer(0)]],\n"
        @"    device const float* A [[buffer(1)]],\n"
        @"    device const ushort* gateW [[buffer(2)]],\n"
        @"    device const ushort* upW [[buffer(3)]],\n"
        @"    constant uint& K [[buffer(4)]],\n"
        @"    constant uint& N [[buffer(5)]],\n"
        @"    constant uint& activationKind [[buffer(6)]],\n"
        @"    uint group [[threadgroup_position_in_grid]],\n"
        @"    uint tid [[thread_position_in_threadgroup]]) {\n"
        @"    uint row0 = group * 4u;\n"
        @"    uint row1 = row0 + 1u;\n"
        @"    uint row2 = row0 + 2u;\n"
        @"    uint row3 = row0 + 3u;\n"
        @"    if (row0 >= N) return;\n"
        @"    bool has1 = row1 < N;\n"
        @"    bool has2 = row2 < N;\n"
        @"    bool has3 = row3 < N;\n"
        @"    uint base0 = row0 * K;\n"
        @"    uint base1 = row1 * K;\n"
        @"    uint base2 = row2 * K;\n"
        @"    uint base3 = row3 * K;\n"
        @"    float g0 = 0.0f, g1 = 0.0f, g2 = 0.0f, g3 = 0.0f;\n"
        @"    float u0 = 0.0f, u1 = 0.0f, u2 = 0.0f, u3 = 0.0f;\n"
        @"    for (uint k = tid; k < K; k += GOLLEK_MATVEC_THREADS) {\n"
        @"        float av = A[k];\n"
        @"        g0 += av * gollek_bf16_to_float(gateW[base0 + k]);\n"
        @"        u0 += av * gollek_bf16_to_float(upW[base0 + k]);\n"
        @"        if (has1) {\n"
        @"            g1 += av * gollek_bf16_to_float(gateW[base1 + k]);\n"
        @"            u1 += av * gollek_bf16_to_float(upW[base1 + k]);\n"
        @"        }\n"
        @"        if (has2) {\n"
        @"            g2 += av * gollek_bf16_to_float(gateW[base2 + k]);\n"
        @"            u2 += av * gollek_bf16_to_float(upW[base2 + k]);\n"
        @"        }\n"
        @"        if (has3) {\n"
        @"            g3 += av * gollek_bf16_to_float(gateW[base3 + k]);\n"
        @"            u3 += av * gollek_bf16_to_float(upW[base3 + k]);\n"
        @"        }\n"
        @"    }\n"
        @"    threadgroup float pg0[GOLLEK_MATVEC_THREADS];\n"
        @"    threadgroup float pg1[GOLLEK_MATVEC_THREADS];\n"
        @"    threadgroup float pg2[GOLLEK_MATVEC_THREADS];\n"
        @"    threadgroup float pg3[GOLLEK_MATVEC_THREADS];\n"
        @"    threadgroup float pu0[GOLLEK_MATVEC_THREADS];\n"
        @"    threadgroup float pu1[GOLLEK_MATVEC_THREADS];\n"
        @"    threadgroup float pu2[GOLLEK_MATVEC_THREADS];\n"
        @"    threadgroup float pu3[GOLLEK_MATVEC_THREADS];\n"
        @"    pg0[tid] = g0; pg1[tid] = g1; pg2[tid] = g2; pg3[tid] = g3;\n"
        @"    pu0[tid] = u0; pu1[tid] = u1; pu2[tid] = u2; pu3[tid] = u3;\n"
        @"    threadgroup_barrier(mem_flags::mem_threadgroup);\n"
        @"    for (uint stride = GOLLEK_MATVEC_THREADS >> 1; stride > 0; stride >>= 1) {\n"
        @"        if (tid < stride) {\n"
        @"            pg0[tid] += pg0[tid + stride]; pg1[tid] += pg1[tid + stride];\n"
        @"            pg2[tid] += pg2[tid + stride]; pg3[tid] += pg3[tid + stride];\n"
        @"            pu0[tid] += pu0[tid + stride]; pu1[tid] += pu1[tid + stride];\n"
        @"            pu2[tid] += pu2[tid + stride]; pu3[tid] += pu3[tid + stride];\n"
        @"        }\n"
        @"        threadgroup_barrier(mem_flags::mem_threadgroup);\n"
        @"    }\n"
        @"    if (tid == 0) {\n"
        @"        C[row0] = gollek_gated_activation(pg0[0], pu0[0], activationKind);\n"
        @"        if (has1) C[row1] = gollek_gated_activation(pg1[0], pu1[0], activationKind);\n"
        @"        if (has2) C[row2] = gollek_gated_activation(pg2[0], pu2[0], activationKind);\n"
        @"        if (has3) C[row3] = gollek_gated_activation(pg3[0], pu3[0], activationKind);\n"
        @"    }\n"
        @"}\n"
        @"kernel void gollek_matvec_tb_bf16_gated_pair_simd_kernel(\n"
        @"    device float* C [[buffer(0)]],\n"
        @"    device const float* A [[buffer(1)]],\n"
        @"    device const ushort* gateW [[buffer(2)]],\n"
        @"    device const ushort* upW [[buffer(3)]],\n"
        @"    constant uint& K [[buffer(4)]],\n"
        @"    constant uint& N [[buffer(5)]],\n"
        @"    constant uint& activationKind [[buffer(6)]],\n"
        @"    uint gid [[threadgroup_position_in_grid]],\n"
        @"    uint tid [[thread_position_in_threadgroup]],\n"
        @"    uint lane [[thread_index_in_simdgroup]],\n"
        @"    uint sg [[simdgroup_index_in_threadgroup]]) {\n"
        @"    if (gid >= N) return;\n"
        @"    uint base = gid * K;\n"
        @"    float gate = 0.0f;\n"
        @"    float up = 0.0f;\n"
        @"    for (uint k = tid; k < K; k += GOLLEK_MATVEC_THREADS) {\n"
        @"        float av = A[k];\n"
        @"        gate += av * gollek_bf16_to_float(gateW[base + k]);\n"
        @"        up += av * gollek_bf16_to_float(upW[base + k]);\n"
        @"    }\n"
        @"    threadgroup float partialGate[8];\n"
        @"    threadgroup float partialUp[8];\n"
        @"    float rowGate = simd_sum(gate);\n"
        @"    float rowUp = simd_sum(up);\n"
        @"    if (lane == 0u) {\n"
        @"        partialGate[sg] = rowGate;\n"
        @"        partialUp[sg] = rowUp;\n"
        @"    }\n"
        @"    threadgroup_barrier(mem_flags::mem_threadgroup);\n"
        @"    if (sg == 0u) {\n"
        @"        uint groups = GOLLEK_MATVEC_THREADS / 32u;\n"
        @"        float g = lane < groups ? partialGate[lane] : 0.0f;\n"
        @"        float u = lane < groups ? partialUp[lane] : 0.0f;\n"
        @"        g = simd_sum(g);\n"
        @"        u = simd_sum(u);\n"
        @"        if (lane == 0u) C[gid] = gollek_gated_activation(g, u, activationKind);\n"
        @"    }\n"
        @"}\n"
        @"kernel void gollek_matvec_tb_bf16_triple_mixed_kernel(\n"
        @"    device float* C0 [[buffer(0)]],\n"
        @"    device float* C1 [[buffer(1)]],\n"
        @"    device float* C2 [[buffer(2)]],\n"
        @"    device const float* A [[buffer(3)]],\n"
        @"    device const ushort* B0 [[buffer(4)]],\n"
        @"    device const ushort* B1 [[buffer(5)]],\n"
        @"    device const ushort* B2 [[buffer(6)]],\n"
        @"    constant uint& K [[buffer(7)]],\n"
        @"    constant uint& N0 [[buffer(8)]],\n"
        @"    constant uint& N1 [[buffer(9)]],\n"
        @"    constant uint& N2 [[buffer(10)]],\n"
        @"    uint gid [[threadgroup_position_in_grid]],\n"
        @"    uint tid [[thread_position_in_threadgroup]]) {\n"
        @"    uint total = N0 + N1 + N2;\n"
        @"    if (gid >= total) return;\n"
        @"    device const ushort* B = B0;\n"
        @"    device float* C = C0;\n"
        @"    uint local = gid;\n"
        @"    if (gid >= N0 + N1) {\n"
        @"        B = B2;\n"
        @"        C = C2;\n"
        @"        local = gid - N0 - N1;\n"
        @"    } else if (gid >= N0) {\n"
        @"        B = B1;\n"
        @"        C = C1;\n"
        @"        local = gid - N0;\n"
        @"    }\n"
        @"    uint base = local * K;\n"
        @"    float sum = 0.0f;\n"
        @"    for (uint k = tid; k < K; k += GOLLEK_MATVEC_THREADS) {\n"
        @"        sum += A[k] * gollek_bf16_to_float(B[base + k]);\n"
        @"    }\n"
        @"    threadgroup float partial[GOLLEK_MATVEC_THREADS];\n"
        @"    partial[tid] = sum;\n"
        @"    threadgroup_barrier(mem_flags::mem_threadgroup);\n"
        @"    for (uint stride = GOLLEK_MATVEC_THREADS >> 1; stride > 0; stride >>= 1) {\n"
        @"        if (tid < stride) partial[tid] += partial[tid + stride];\n"
        @"        threadgroup_barrier(mem_flags::mem_threadgroup);\n"
        @"    }\n"
        @"    if (tid == 0) C[local] = partial[0];\n"
        @"}\n"
        @"kernel void gollek_matvec_tb_bf16_triple_mixed_x4_kernel(\n"
        @"    device float* C0 [[buffer(0)]],\n"
        @"    device float* C1 [[buffer(1)]],\n"
        @"    device float* C2 [[buffer(2)]],\n"
        @"    device const float* A [[buffer(3)]],\n"
        @"    device const ushort* B0 [[buffer(4)]],\n"
        @"    device const ushort* B1 [[buffer(5)]],\n"
        @"    device const ushort* B2 [[buffer(6)]],\n"
        @"    constant uint& K [[buffer(7)]],\n"
        @"    constant uint& N0 [[buffer(8)]],\n"
        @"    constant uint& N1 [[buffer(9)]],\n"
        @"    constant uint& N2 [[buffer(10)]],\n"
        @"    uint group [[threadgroup_position_in_grid]],\n"
        @"    uint tid [[thread_position_in_threadgroup]]) {\n"
        @"    uint total = N0 + N1 + N2;\n"
        @"    uint row0 = group * 4u;\n"
        @"    uint row1 = row0 + 1u;\n"
        @"    uint row2 = row0 + 2u;\n"
        @"    uint row3 = row0 + 3u;\n"
        @"    if (row0 >= total) return;\n"
        @"    bool has1 = row1 < total;\n"
        @"    bool has2 = row2 < total;\n"
        @"    bool has3 = row3 < total;\n"
        @"    device const ushort* W0 = B0;\n"
        @"    device const ushort* W1 = B0;\n"
        @"    device const ushort* W2 = B0;\n"
        @"    device const ushort* W3 = B0;\n"
        @"    device float* O0 = C0;\n"
        @"    device float* O1 = C0;\n"
        @"    device float* O2 = C0;\n"
        @"    device float* O3 = C0;\n"
        @"    uint local0 = row0;\n"
        @"    uint local1 = row1;\n"
        @"    uint local2 = row2;\n"
        @"    uint local3 = row3;\n"
        @"    if (row0 >= N0 + N1) { W0 = B2; O0 = C2; local0 = row0 - N0 - N1; }\n"
        @"    else if (row0 >= N0) { W0 = B1; O0 = C1; local0 = row0 - N0; }\n"
        @"    if (has1) {\n"
        @"        if (row1 >= N0 + N1) { W1 = B2; O1 = C2; local1 = row1 - N0 - N1; }\n"
        @"        else if (row1 >= N0) { W1 = B1; O1 = C1; local1 = row1 - N0; }\n"
        @"    }\n"
        @"    if (has2) {\n"
        @"        if (row2 >= N0 + N1) { W2 = B2; O2 = C2; local2 = row2 - N0 - N1; }\n"
        @"        else if (row2 >= N0) { W2 = B1; O2 = C1; local2 = row2 - N0; }\n"
        @"    }\n"
        @"    if (has3) {\n"
        @"        if (row3 >= N0 + N1) { W3 = B2; O3 = C2; local3 = row3 - N0 - N1; }\n"
        @"        else if (row3 >= N0) { W3 = B1; O3 = C1; local3 = row3 - N0; }\n"
        @"    }\n"
        @"    uint base0 = local0 * K;\n"
        @"    uint base1 = local1 * K;\n"
        @"    uint base2 = local2 * K;\n"
        @"    uint base3 = local3 * K;\n"
        @"    float sum0 = 0.0f;\n"
        @"    float sum1 = 0.0f;\n"
        @"    float sum2 = 0.0f;\n"
        @"    float sum3 = 0.0f;\n"
        @"    for (uint k = tid; k < K; k += GOLLEK_MATVEC_THREADS) {\n"
        @"        float av = A[k];\n"
        @"        sum0 += av * gollek_bf16_to_float(W0[base0 + k]);\n"
        @"        if (has1) sum1 += av * gollek_bf16_to_float(W1[base1 + k]);\n"
        @"        if (has2) sum2 += av * gollek_bf16_to_float(W2[base2 + k]);\n"
        @"        if (has3) sum3 += av * gollek_bf16_to_float(W3[base3 + k]);\n"
        @"    }\n"
        @"    threadgroup float p0[GOLLEK_MATVEC_THREADS];\n"
        @"    threadgroup float p1[GOLLEK_MATVEC_THREADS];\n"
        @"    threadgroup float p2[GOLLEK_MATVEC_THREADS];\n"
        @"    threadgroup float p3[GOLLEK_MATVEC_THREADS];\n"
        @"    p0[tid] = sum0;\n"
        @"    p1[tid] = sum1;\n"
        @"    p2[tid] = sum2;\n"
        @"    p3[tid] = sum3;\n"
        @"    threadgroup_barrier(mem_flags::mem_threadgroup);\n"
        @"    for (uint stride = GOLLEK_MATVEC_THREADS >> 1; stride > 0; stride >>= 1) {\n"
        @"        if (tid < stride) {\n"
        @"            p0[tid] += p0[tid + stride];\n"
        @"            p1[tid] += p1[tid + stride];\n"
        @"            p2[tid] += p2[tid + stride];\n"
        @"            p3[tid] += p3[tid + stride];\n"
        @"        }\n"
        @"        threadgroup_barrier(mem_flags::mem_threadgroup);\n"
        @"    }\n"
        @"    if (tid == 0) {\n"
        @"        O0[local0] = p0[0];\n"
        @"        if (has1) O1[local1] = p1[0];\n"
        @"        if (has2) O2[local2] = p2[0];\n"
        @"        if (has3) O3[local3] = p3[0];\n"
        @"    }\n"
        @"}\n"
        @"kernel void gollek_matvec_t_half_kernel(\n"
        @"    device float* C [[buffer(0)]],\n"
        @"    device const float* A [[buffer(1)]],\n"
        @"    device const half* B [[buffer(2)]],\n"
        @"    constant uint& K [[buffer(3)]],\n"
        @"    constant uint& N [[buffer(4)]],\n"
        @"    uint gid [[threadgroup_position_in_grid]],\n"
        @"    uint tid [[thread_position_in_threadgroup]]) {\n"
        @"    if (gid >= N) return;\n"
        @"    float sum = 0.0f;\n"
        @"    for (uint k = tid; k < K; k += GOLLEK_MATVEC_THREADS) {\n"
        @"        sum += A[k] * float(B[k * N + gid]);\n"
        @"    }\n"
        @"    threadgroup float partial[GOLLEK_MATVEC_THREADS];\n"
        @"    partial[tid] = sum;\n"
        @"    threadgroup_barrier(mem_flags::mem_threadgroup);\n"
        @"    for (uint stride = GOLLEK_MATVEC_THREADS >> 1; stride > 0; stride >>= 1) {\n"
        @"        if (tid < stride) partial[tid] += partial[tid + stride];\n"
        @"        threadgroup_barrier(mem_flags::mem_threadgroup);\n"
        @"    }\n"
        @"    if (tid == 0) C[gid] = partial[0];\n"
        @"}\n",
        (unsigned long)threads];
}
