/*
 * Copyright (c) 2026 Kayys.tech
 */
package tech.kayys.gollek.spi.runtime;

import java.util.List;

/**
 * Strategy for verifying speculative tokens proposed by a draft model.
 * The high-integrity model uses this logic to determine which parts of 
 * a SpeculativeBatch are mathematically valid.
 */
public interface DraftVerificationStrategy {

    /**
     * Verifies a batch of tokens against the target model's probabilities.
     * 
     * @param batch         the proposed tokens
     * @param targetLogits  the logits generated by the target model for the batch
     * @return the number of valid tokens (0 to batch.size())
     */
    int verify(SpeculativeBatch batch, java.lang.foreign.MemorySegment targetLogits);

    /**
     * Threshold-based strategy (greedy check).
     */
    static DraftVerificationStrategy greedy() {
        return (batch, targetLogits) -> {
            // Implementation: check if draft token is the argmax of target logits
            return 0; // Placeholder
        };
    }
}
