/**
 * gollek_engine.ts
 * TypeScript API for the Gollek Wasm inference engine.
 *
 * Usage (browser or Node.js):
 *   import { createGollekEngine } from './gollek_engine';
 *
 *   const engine = await createGollekEngine();
 *   await engine.loadModelFromUrl('/models/mobilenet_v2.litertlm');
 *   const scores = await engine.infer(pixelData);    // Float32Array
 *   engine.destroy();
 *
 * Copyright (c) 2026 Kayys.tech — MIT License
 */

/* ── Types mirroring C enum GollekDelegate ─────────────────────────────── */
export const enum Delegate {
  None = 0,
  CPU = 1,
  GPU = 2,   // WebGPU delegate (future) or CPU fallback
  Auto = 6,
}

export interface GollekEngineOptions {
  numThreads?: number;    // default 4
  delegate?: Delegate;  // default Auto
  enableXnnpack?: boolean;   // default true
  useMemoryPool?: boolean;   // default true
}

export interface TensorInfo {
  name: string;
  type: number;
  dims: number[];
  byteSize: number;
  scale: number;
  zeroPoint: number;
}

/* ── Wasm module interface (auto-generated by Emscripten) ──────────────── */
interface WasmGollekEngine {
  loadModelFromBuffer(data: Uint8Array): number;
  inputCount(): number;
  outputCount(): number;
  getInputInfo(i: number): object | null;
  getOutputInfo(i: number): object | null;
  setInput(i: number, data: Uint8Array): number;
  invoke(): number;
  getOutput(i: number): Uint8Array | null;
  infer(input: Uint8Array): Uint8Array | null;
  lastError(): string;
  version(): string;
  delete(): void;
}

interface GollekWasmModule {
  GollekEngine: {
    new(numThreads: number, delegate: number,
      enableXnnpack: boolean, useMemoryPool: boolean): WasmGollekEngine;
  };
}

/* ── Public API ────────────────────────────────────────────────────────── */

export class GollekEngine {
  private native: WasmGollekEngine;

  private constructor(native: WasmGollekEngine) {
    this.native = native;
  }

  // ── Factory ──────────────────────────────────────────────────────────

  /**
   * Load the Wasm module and create an engine instance.
   * @param wasmPath  Path to gollek_core.js (the Emscripten loader).
   */
  static async create(
    wasmPath = './gollek_core.js',
    options: GollekEngineOptions = {},
  ): Promise<GollekEngine> {
    const mod: GollekWasmModule = await loadWasmModule(wasmPath);
    const native = new mod.GollekEngine(
      options.numThreads ?? 4,
      options.delegate ?? Delegate.Auto,
      options.enableXnnpack ?? true,
      options.useMemoryPool ?? true,
    );
    return new GollekEngine(native);
  }

  // ── Model loading ─────────────────────────────────────────────────────

  async loadModelFromUrl(url: string): Promise<void> {
    const resp = await fetch(url);
    if (!resp.ok) throw new Error(`Failed to fetch model: ${url} → ${resp.status}`);
    const buffer = await resp.arrayBuffer();
    const status = this.native.loadModelFromBuffer(new Uint8Array(buffer));
    if (status !== 0) throw new Error(`loadModelFromBuffer failed: ${this.native.lastError()}`);
  }

  loadModelFromBytes(bytes: Uint8Array): void {
    const status = this.native.loadModelFromBuffer(bytes);
    if (status !== 0) throw new Error(`loadModelFromBuffer failed: ${this.native.lastError()}`);
  }

  // ── Tensor info ───────────────────────────────────────────────────────

  get inputCount(): number { return this.native.inputCount(); }
  get outputCount(): number { return this.native.outputCount(); }

  getInputInfo(index = 0): TensorInfo | null { return this.native.getInputInfo(index) as TensorInfo | null; }
  getOutputInfo(index = 0): TensorInfo | null { return this.native.getOutputInfo(index) as TensorInfo | null; }

  // ── Inference ─────────────────────────────────────────────────────────

  setInput(index: number, data: Uint8Array): void {
    const s = this.native.setInput(index, data);
    if (s !== 0) throw new Error(`setInput failed: ${this.native.lastError()}`);
  }

  invoke(): void {
    const s = this.native.invoke();
    if (s !== 0) throw new Error(`invoke failed: ${this.native.lastError()}`);
  }

  getOutput(index = 0): Uint8Array {
    const out = this.native.getOutput(index);
    if (!out) throw new Error(`getOutput failed: ${this.native.lastError()}`);
    return out;
  }

  /**
   * Convenience: set input 0 → invoke → return output 0 as a typed array.
   * For float models: `new Float32Array(engine.infer(input).buffer)`
   */
  infer(input: Uint8Array): Uint8Array {
    const out = this.native.infer(input);
    if (!out) throw new Error(`infer failed: ${this.native.lastError()}`);
    return out;
  }

  /** Run inference and return result as Float32Array (convenience). */
  inferFloat32(input: Float32Array): Float32Array {
    const raw = this.infer(new Uint8Array(input.buffer, input.byteOffset, input.byteLength));
    return new Float32Array(raw.buffer, raw.byteOffset, raw.byteLength / 4);
  }

  // ── Preprocessing helpers ─────────────────────────────────────────────

  /**
   * Normalize a Uint8 image [0..255] → Float32 [-1..1] or [0..1].
   * Suitable for MobileNet-style models.
   */
  static normalizeImageUint8(
    pixels: Uint8ClampedArray | Uint8Array,
    mean = 127.5,
    std = 127.5,
  ): Float32Array {
    const out = new Float32Array(pixels.length);
    for (let i = 0; i < pixels.length; ++i) out[i] = (pixels[i] - mean) / std;
    return out;
  }

  /**
   * Extract RGBA pixels from a canvas element → Float32 tensor [1, H, W, 3].
   */
  static canvasToTensor(canvas: HTMLCanvasElement): Float32Array {
    const ctx = canvas.getContext('2d')!;
    const { width, height } = canvas;
    const rgba = ctx.getImageData(0, 0, width, height).data;  // Uint8ClampedArray RGBA

    const tensor = new Float32Array(width * height * 3);
    let ti = 0;
    for (let i = 0; i < rgba.length; i += 4) {
      tensor[ti++] = (rgba[i] - 127.5) / 127.5;  // R
      tensor[ti++] = (rgba[i + 1] - 127.5) / 127.5;  // G
      tensor[ti++] = (rgba[i + 2] - 127.5) / 127.5;  // B
      // Skip alpha
    }
    return tensor;
  }

  // ── Diagnostics ───────────────────────────────────────────────────────

  get lastError(): string { return this.native.lastError(); }
  get version(): string { return this.native.version(); }

  // ── Lifecycle ─────────────────────────────────────────────────────────

  destroy(): void { this.native.delete(); }
}

/* ── Internal: Wasm module loader ─────────────────────────────────────── */

let _cachedModule: GollekWasmModule | null = null;

async function loadWasmModule(loaderPath: string): Promise<GollekWasmModule> {
  if (_cachedModule) return _cachedModule;

  // Dynamic import works in modern browsers and Node 18+
  const loaderFactory = (await import(/* @vite-ignore */ loaderPath)).default;
  _cachedModule = await loaderFactory() as GollekWasmModule;
  return _cachedModule;
}
