package tech.kayys.gollek.multimodal;

import io.micrometer.core.instrument.*;
import jakarta.enterprise.context.ApplicationScoped;
import jakarta.inject.Inject;
import tech.kayys.gollek.spi.model.ModalityType;
import tech.kayys.gollek.spi.model.MultimodalRequest;
import tech.kayys.gollek.spi.model.MultimodalResponse;

import java.time.Duration;
import java.util.Map;
import java.util.Set;
import java.util.concurrent.ConcurrentHashMap;

/**
 * Micrometer-based metrics collector for multimodal inference operations.
 *
 * <p>Records all operational metrics needed for dashboards and SLO monitoring.
 * All metrics are prefixed with {@code gollek.multimodal.*}.
 *
 * <h3>Metrics emitted</h3>
 * <table>
 *   <tr><th>Metric</th><th>Type</th><th>Description</th></tr>
 *   <tr><td>gollek.multimodal.requests.total</td><td>Counter</td><td>Total inference requests by provider, modalities, status</td></tr>
 *   <tr><td>gollek.multimodal.latency</td><td>Timer</td><td>E2E latency per provider and modality combination</td></tr>
 *   <tr><td>gollek.multimodal.tokens.input</td><td>DistributionSummary</td><td>Input token distribution</td></tr>
 *   <tr><td>gollek.multimodal.tokens.output</td><td>DistributionSummary</td><td>Output token distribution</td></tr>
 *   <tr><td>gollek.multimodal.fallbacks.total</td><td>Counter</td><td>Fallback activations per provider pair</td></tr>
 *   <tr><td>gollek.multimodal.errors.total</td><td>Counter</td><td>Errors by provider and error code</td></tr>
 *   <tr><td>gollek.multimodal.sessions.active</td><td>Gauge</td><td>Active conversation sessions</td></tr>
 *   <tr><td>gollek.multimodal.images.generated</td><td>Counter</td><td>Images generated by provider and size</td></tr>
 *   <tr><td>gollek.multimodal.tts.chars</td><td>Counter</td><td>Characters synthesized by voice</td></tr>
 * </table>
 */
@ApplicationScoped
public class MultimodalMetrics {

    // Metric name constants
    public static final String M_REQUESTS   = "gollek.multimodal.requests.total";
    public static final String M_LATENCY    = "gollek.multimodal.latency";
    public static final String M_TOK_IN     = "gollek.multimodal.tokens.input";
    public static final String M_TOK_OUT    = "gollek.multimodal.tokens.output";
    public static final String M_FALLBACKS  = "gollek.multimodal.fallbacks.total";
    public static final String M_ERRORS     = "gollek.multimodal.errors.total";
    public static final String M_SESSIONS   = "gollek.multimodal.sessions.active";
    public static final String M_IMAGES     = "gollek.multimodal.images.generated";
    public static final String M_TTS_CHARS  = "gollek.multimodal.tts.chars";

    @Inject
    MeterRegistry registry;

    // Track active session count separately (gauge requires live reference)
    private final Map<String, Long> activeSessions = new ConcurrentHashMap<>();

    // -------------------------------------------------------------------------
    // Inference metrics
    // -------------------------------------------------------------------------

    /**
     * Record a completed inference call.
     *
     * @param request    the original request
     * @param response   the response received
     * @param startNanos start timestamp from {@link System#nanoTime()}
     */
    public void recordInference(MultimodalRequest request,
                                 MultimodalResponse response,
                                 long startNanos) {
        String provider = response.getModel();
        String status   = response.getStatus().name().toLowerCase();
        String modalities = modalityTag(request.inputModalities());

        // Request counter
        Counter.builder(M_REQUESTS)
                .tag("provider", provider)
                .tag("modalities", modalities)
                .tag("status", status)
                .description("Total multimodal inference requests")
                .register(registry)
                .increment();

        // Latency timer
        long elapsedNs = System.nanoTime() - startNanos;
        Timer.builder(M_LATENCY)
                .tag("provider", provider)
                .tag("modalities", modalities)
                .description("End-to-end inference latency")
                .publishPercentiles(0.5, 0.95, 0.99)
                .register(registry)
                .record(Duration.ofNanos(elapsedNs));

        // Token distributions
        if (response.getUsage() != null) {
            DistributionSummary.builder(M_TOK_IN)
                    .tag("provider", provider)
                    .description("Input token count distribution")
                    .register(registry)
                    .record(response.getUsage().getInputTokens());

            DistributionSummary.builder(M_TOK_OUT)
                    .tag("provider", provider)
                    .description("Output token count distribution")
                    .register(registry)
                    .record(response.getUsage().getOutputTokens());
        }

        // Fallback counter
        if (response.getStatus() == MultimodalResponse.ResponseStatus.FALLBACK) {
            String fallbackFrom = (String) response.getMetadata().get("fallbackFrom");
            Counter.builder(M_FALLBACKS)
                    .tag("primary",  fallbackFrom != null ? fallbackFrom : "unknown")
                    .tag("fallback", provider)
                    .description("Provider fallback activations")
                    .register(registry)
                    .increment();
        }

        // Error counter
        if (response.getStatus() == MultimodalResponse.ResponseStatus.ERROR) {
            Counter.builder(M_ERRORS)
                    .tag("provider",   provider)
                    .tag("error_code", response.getMetadata().get("error_code") != null
                            ? (String) response.getMetadata().get("error_code") : "UNKNOWN")
                    .description("Inference errors by provider and code")
                    .register(registry)
                    .increment();
        }
    }

    // -------------------------------------------------------------------------
    // Image generation metrics
    // -------------------------------------------------------------------------

    public void recordImageGeneration(String provider, int width, int height, int count) {
        String size = width + "x" + height;
        Counter.builder(M_IMAGES)
                .tag("provider", provider)
                .tag("size", size)
                .description("Images generated")
                .register(registry)
                .increment(count);
    }

    // -------------------------------------------------------------------------
    // TTS metrics
    // -------------------------------------------------------------------------

    public void recordTts(String provider, String voice, int charCount) {
        Counter.builder(M_TTS_CHARS)
                .tag("provider", provider)
                .tag("voice", voice != null ? voice : "default")
                .description("Characters synthesized via TTS")
                .register(registry)
                .increment(charCount);
    }

    // -------------------------------------------------------------------------
    // Session gauge
    // -------------------------------------------------------------------------

    public void sessionCreated(String sessionId) {
        activeSessions.put(sessionId, System.currentTimeMillis());
        updateSessionGauge();
    }

    public void sessionDeleted(String sessionId) {
        activeSessions.remove(sessionId);
        updateSessionGauge();
    }

    private void updateSessionGauge() {
        Gauge.builder(M_SESSIONS, activeSessions, Map::size)
                .description("Active multimodal conversation sessions")
                .register(registry);
    }

    // -------------------------------------------------------------------------
    // Helpers
    // -------------------------------------------------------------------------

    private String modalityTag(Set<ModalityType> modalities) {
        if (modalities.size() == 1) return modalities.iterator().next().name().toLowerCase();
        if (modalities.contains(ModalityType.IMAGE) && modalities.contains(ModalityType.TEXT))
            return "text+image";
        if (modalities.contains(ModalityType.AUDIO)) return "audio";
        if (modalities.contains(ModalityType.VIDEO)) return "video";
        return "mixed";
    }
}
