// Generated by jextract

package tech.kayys.gollek.llama;

import java.lang.invoke.*;
import java.lang.foreign.*;

/**
 * {@snippet lang = c :
 * typedef void (*ggml_custom2_op_t)(struct ggml_tensor {
 *     enum ggml_type type;
 *     struct ggml_backend_buffer *buffer;
 *     int64_t ne[4];
 *     size_t nb[4];
 *     enum ggml_op op;
 *     int32_t op_params[16];
 *     int32_t flags;
 *     struct ggml_tensor *src[10];
 *     struct ggml_tensor *view_src;
 *     size_t view_offs;
 *     void *data;
 *     char name[64];
 *     void *extra;
 *     char padding[8];
 * } *, const struct ggml_tensor {
 *     enum ggml_type type;
 *     struct ggml_backend_buffer *buffer;
 *     int64_t ne[4];
 *     size_t nb[4];
 *     enum ggml_op op;
 *     int32_t op_params[16];
 *     int32_t flags;
 *     struct ggml_tensor *src[10];
 *     struct ggml_tensor *view_src;
 *     size_t view_offs;
 *     void *data;
 *     char name[64];
 *     void *extra;
 *     char padding[8];
 * } *, const struct ggml_tensor {
 *     enum ggml_type type;
 *     struct ggml_backend_buffer *buffer;
 *     int64_t ne[4];
 *     size_t nb[4];
 *     enum ggml_op op;
 *     int32_t op_params[16];
 *     int32_t flags;
 *     struct ggml_tensor *src[10];
 *     struct ggml_tensor *view_src;
 *     size_t view_offs;
 *     void *data;
 *     char name[64];
 *     void *extra;
 *     char padding[8];
 * } *, int, int, void *)
 * }
 */
public class ggml_custom2_op_t {

    ggml_custom2_op_t() {
        // Should not be called directly
    }

    /**
     * The function pointer signature, expressed as a functional interface
     */
    public interface Function {
        void apply(MemorySegment dst, MemorySegment a, MemorySegment b, int ith, int nth, MemorySegment userdata);
    }

    private static final FunctionDescriptor $DESC = FunctionDescriptor.ofVoid(
            llama_h.C_POINTER,
            llama_h.C_POINTER,
            llama_h.C_POINTER,
            llama_h.C_INT,
            llama_h.C_INT,
            llama_h.C_POINTER);

    /**
     * The descriptor of this function pointer
     */
    public static FunctionDescriptor descriptor() {
        return $DESC;
    }

    private static final MethodHandle UP$MH = llama_h.upcallHandle(ggml_custom2_op_t.Function.class, "apply", $DESC);

    /**
     * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
     * The lifetime of the returned segment is managed by {@code arena}
     */
    public static MemorySegment allocate(ggml_custom2_op_t.Function fi, Arena arena) {
        return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
    }

    private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

    /**
     * Invoke the upcall stub {@code funcPtr}, with given parameters
     */
    public static void invoke(MemorySegment funcPtr, MemorySegment dst, MemorySegment a, MemorySegment b, int ith,
            int nth, MemorySegment userdata) {
        try {
            DOWN$MH.invokeExact(funcPtr, dst, a, b, ith, nth, userdata);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
}
