// Generated by jextract

package tech.kayys.gollek.llama;

import java.lang.invoke.*;
import java.lang.foreign.*;

/**
 * {@snippet lang = c :
 * typedef void (*ggml_log_callback)(enum ggml_log_level {
 *     GGML_LOG_LEVEL_NONE = 0,
 *     GGML_LOG_LEVEL_DEBUG = 1,
 *     GGML_LOG_LEVEL_INFO = 2,
 *     GGML_LOG_LEVEL_WARN = 3,
 *     GGML_LOG_LEVEL_ERROR = 4,
 *     GGML_LOG_LEVEL_CONT = 5
 * }, const char *, void *)
 * }
 */
public class ggml_log_callback {

    ggml_log_callback() {
        // Should not be called directly
    }

    /**
     * The function pointer signature, expressed as a functional interface
     */
    public interface Function {
        void apply(int level, MemorySegment text, MemorySegment user_data);
    }

    private static final FunctionDescriptor $DESC = FunctionDescriptor.ofVoid(
            llama_h.C_INT,
            llama_h.C_POINTER,
            llama_h.C_POINTER);

    /**
     * The descriptor of this function pointer
     */
    public static FunctionDescriptor descriptor() {
        return $DESC;
    }

    private static final MethodHandle UP$MH = llama_h.upcallHandle(ggml_log_callback.Function.class, "apply", $DESC);

    /**
     * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
     * The lifetime of the returned segment is managed by {@code arena}
     */
    public static MemorySegment allocate(ggml_log_callback.Function fi, Arena arena) {
        return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
    }

    private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

    /**
     * Invoke the upcall stub {@code funcPtr}, with given parameters
     */
    public static void invoke(MemorySegment funcPtr, int level, MemorySegment text, MemorySegment user_data) {
        try {
            DOWN$MH.invokeExact(funcPtr, level, text, user_data);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
}
