// Generated by jextract

package tech.kayys.gollek.llama;

import java.lang.invoke.*;
import java.lang.foreign.*;

/**
 * {@snippet lang = c
 * : * typedef void (*ggml_vec_dot_t)(int, float *restrict, size_t, const void *restrict, size_t, const void *restrict, size_t, int)
 * }
 */
public class ggml_vec_dot_t {

    ggml_vec_dot_t() {
        // Should not be called directly
    }

    /**
     * The function pointer signature, expressed as a functional interface
     */
    public interface Function {
        void apply(int n, MemorySegment s, long bs, MemorySegment x, long bx, MemorySegment y, long by, int nrc);
    }

    private static final FunctionDescriptor $DESC = FunctionDescriptor.ofVoid(
            llama_h.C_INT,
            llama_h.C_POINTER,
            llama_h.C_LONG,
            llama_h.C_POINTER,
            llama_h.C_LONG,
            llama_h.C_POINTER,
            llama_h.C_LONG,
            llama_h.C_INT);

    /**
     * The descriptor of this function pointer
     */
    public static FunctionDescriptor descriptor() {
        return $DESC;
    }

    private static final MethodHandle UP$MH = llama_h.upcallHandle(ggml_vec_dot_t.Function.class, "apply", $DESC);

    /**
     * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
     * The lifetime of the returned segment is managed by {@code arena}
     */
    public static MemorySegment allocate(ggml_vec_dot_t.Function fi, Arena arena) {
        return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
    }

    private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

    /**
     * Invoke the upcall stub {@code funcPtr}, with given parameters
     */
    public static void invoke(MemorySegment funcPtr, int n, MemorySegment s, long bs, MemorySegment x, long bx,
            MemorySegment y, long by, int nrc) {
        try {
            DOWN$MH.invokeExact(funcPtr, n, s, bs, x, bx, y, by, nrc);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
}
