// Generated by jextract

package tech.kayys.gollek.llama;

import java.lang.invoke.*;
import java.lang.foreign.*;

/**
 * {@snippet lang = c
 * : * typedef ggml_backend_buffer_type_t (*ggml_backend_split_buffer_type_t)(int, const float *)
 * }
 */
public class ggml_backend_split_buffer_type_t {

    ggml_backend_split_buffer_type_t() {
        // Should not be called directly
    }

    /**
     * The function pointer signature, expressed as a functional interface
     */
    public interface Function {
        MemorySegment apply(int main_device, MemorySegment tensor_split);
    }

    private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            llama_h.C_POINTER,
            llama_h.C_INT,
            llama_h.C_POINTER);

    /**
     * The descriptor of this function pointer
     */
    public static FunctionDescriptor descriptor() {
        return $DESC;
    }

    private static final MethodHandle UP$MH = llama_h.upcallHandle(ggml_backend_split_buffer_type_t.Function.class,
            "apply", $DESC);

    /**
     * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
     * The lifetime of the returned segment is managed by {@code arena}
     */
    public static MemorySegment allocate(ggml_backend_split_buffer_type_t.Function fi, Arena arena) {
        return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
    }

    private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

    /**
     * Invoke the upcall stub {@code funcPtr}, with given parameters
     */
    public static MemorySegment invoke(MemorySegment funcPtr, int main_device, MemorySegment tensor_split) {
        try {
            return (MemorySegment) DOWN$MH.invokeExact(funcPtr, main_device, tensor_split);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
}
