// Generated by jextract

package tech.kayys.gollek.llama;

import java.lang.invoke.*;
import java.lang.foreign.*;

/**
 * {@snippet lang = c :
 * typedef bool (*llama_opt_param_filter)(const struct ggml_tensor {
 *     enum ggml_type type;
 *     struct ggml_backend_buffer *buffer;
 *     int64_t ne[4];
 *     size_t nb[4];
 *     enum ggml_op op;
 *     int32_t op_params[16];
 *     int32_t flags;
 *     struct ggml_tensor *src[10];
 *     struct ggml_tensor *view_src;
 *     size_t view_offs;
 *     void *data;
 *     char name[64];
 *     void *extra;
 *     char padding[8];
 * } *, void *)
 * }
 */
public class llama_opt_param_filter {

    llama_opt_param_filter() {
        // Should not be called directly
    }

    /**
     * The function pointer signature, expressed as a functional interface
     */
    public interface Function {
        boolean apply(MemorySegment tensor, MemorySegment userdata);
    }

    private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            llama_h.C_BOOL,
            llama_h.C_POINTER,
            llama_h.C_POINTER);

    /**
     * The descriptor of this function pointer
     */
    public static FunctionDescriptor descriptor() {
        return $DESC;
    }

    private static final MethodHandle UP$MH = llama_h.upcallHandle(llama_opt_param_filter.Function.class, "apply",
            $DESC);

    /**
     * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
     * The lifetime of the returned segment is managed by {@code arena}
     */
    public static MemorySegment allocate(llama_opt_param_filter.Function fi, Arena arena) {
        return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
    }

    private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

    /**
     * Invoke the upcall stub {@code funcPtr}, with given parameters
     */
    public static boolean invoke(MemorySegment funcPtr, MemorySegment tensor, MemorySegment userdata) {
        try {
            return (boolean) DOWN$MH.invokeExact(funcPtr, tensor, userdata);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
}
