// Generated by jextract

package tech.kayys.gollek.llama;

import java.lang.foreign.*;
import java.util.function.*;
import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang = c :
 * struct llama_logit_bias {
 *     llama_token token;
 *     float bias;
 * }
 * }
 */
public class llama_logit_bias {

    llama_logit_bias() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
            llama_h.C_INT.withName("token"),
            llama_h.C_FLOAT.withName("bias")).withName("llama_logit_bias");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt token$LAYOUT = (OfInt) $LAYOUT.select(groupElement("token"));

    /**
     * Layout for field:
     * {@snippet lang = c : * llama_token token
     * }
     */
    public static final OfInt token$layout() {
        return token$LAYOUT;
    }

    private static final long token$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang = c : * llama_token token
     * }
     */
    public static final long token$offset() {
        return token$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang = c : * llama_token token
     * }
     */
    public static int token(MemorySegment struct) {
        return struct.get(token$LAYOUT, token$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang = c : * llama_token token
     * }
     */
    public static void token(MemorySegment struct, int fieldValue) {
        struct.set(token$LAYOUT, token$OFFSET, fieldValue);
    }

    private static final OfFloat bias$LAYOUT = (OfFloat) $LAYOUT.select(groupElement("bias"));

    /**
     * Layout for field:
     * {@snippet lang = c : * float bias
     * }
     */
    public static final OfFloat bias$layout() {
        return bias$LAYOUT;
    }

    private static final long bias$OFFSET = 4;

    /**
     * Offset for field:
     * {@snippet lang = c : * float bias
     * }
     */
    public static final long bias$offset() {
        return bias$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang = c : * float bias
     * }
     */
    public static float bias(MemorySegment struct) {
        return struct.get(bias$LAYOUT, bias$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang = c : * float bias
     * }
     */
    public static void bias(MemorySegment struct, float fieldValue) {
        struct.set(bias$LAYOUT, bias$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at
     * {@code index}.
     * The returned segment has address
     * {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() {
        return layout().byteSize();
    }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using
     * {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and
     * {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and
     * {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena,
            Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}
